#!/usr/bin/awk -F, -f

# generated by: awk-csvalid https://github.com/tesera/awk-csvalid

# awk-csvalid csv toolset generator: https://github.com/tesera/awk-csvalid
# usage:
#    validate:     awk -f action=validate validator.awk > violations.txt
#    create table: awk -v action=table -f validator.awk | psql afgo_dev
#    sanitize csv: awk -v action=sanitize -f validator.awk > sanitized.csv
#    insert sql:   awk -v action=insert -f validator.awk | psql afgo_dev

# awk is a simple unix text file parser: http://www.gnu.org/software/gawk/manual/gawk.html
# awk primer:
#    NR = number/index current record
#    RS = record seperator new line i.e. \n
#    FS = field seperator i.e. ,
#    /pattern/ { expression } = if pattern is truthy run expression

BEGIN {
    FS=","; OFS=","; err_count=0; cats["na"]=0;
    if(!action) action = "validate"
    summary_header="file_name,field_name,rule,message,violation_count"
    CSVFILENAME = CSVFILENAME ? CSVFILENAME : FILENAME
    FPAT = "([^,]*)|(\"[^\"]+\")"
}

# builtin helper functions
function eql(x,y) {v=1; for (i in x) v=(v&&x[i]==y[i]); return v;}
function are_headers_valid(valid_headers) { v=0; split($0, h, ","); split(valid_headers, vh, "|"); return eql(h, vh); }
function is_unique(i, val) { if (vals[i,val]) { return 0; } else { vals[i,val] = 1; return 1; } }
function is_integer(x) { return x ~ /^-?[0-9]+$/ }
function is_number(x) { return x ~ /^-?[0-9]+(.[0-9]+)?$/ }
function print_cats(categories) { for (category in categories) { if (categories[category]) print "      " category ": " categories[category]; } }
function log_err(cat) { cats[cat]++; err_count++; }


#get rid of the evil windows cr
{ sub("\r$", "") }


{
     for (i = 1; i <= NF; i++) {
         if (substr($i, 1, 1) == "\"") {
             len = length($i)
             $i = substr($i, 2, len - 2)
         }
     }
}


# make header index/map
NR > 1 {
field_width = 31
    company=$1
    company_plot_number=$2
    measurement_number=$3
    measurement_year=$4
    measurement_month=$5
    measurement_day=$6
    stand_origin=$7
    plot_type=$8
    stand_type=$9
    plot_status=$10
    tree_plot_area=$11
    tree_plot_shape=$12
    tree_tagging_limit=$13
    sapling_plot_area=$14
    sapling_plot_shape=$15
    sapling_tagging_limit_dbh=$16
    sapling_tagging_limit_height=$17
    regen_plot_area=$18
    regen_plot_shape=$19
    regen_tagging_limit_conifer=$20
    regen_tagging_limit_decid=$21
    number_regen_plots=$22
    contractor=$23
    cruiser_1_name=$24
    cruiser_2_name=$25
    shrub_cover=$26
    herb_forb_cover=$27
    grass_cover=$28
    moss_lichen_cover=$29
    avi_field_call=$30
    plot_measurement_comment=$31
}

# awk rules based on user csv ruleset
NR == 1 && action == "validate" { headers="company|company_plot_number|measurement_number|measurement_year|measurement_month|measurement_day|stand_origin|plot_type|stand_type|plot_status|tree_plot_area|tree_plot_shape|tree_tagging_limit|sapling_plot_area|sapling_plot_shape|sapling_tagging_limit_dbh|sapling_tagging_limit_height|regen_plot_area|regen_plot_shape|regen_tagging_limit_conifer|regen_tagging_limit_decid|number_regen_plots|contractor|cruiser_1_name|cruiser_2_name|shrub_cover|herb_forb_cover|grass_cover|moss_lichen_cover|avi_field_call|plot_measurement_comment"; if (!are_headers_valid(headers)) { gsub(/\|/, FS, headers); print  NR FS CSVFILENAME FS "header" FS "invalid-header" FS "error" FS  "headers are invalid "; exit 0;} }
NR == 1 && action == "validate:summary" { headers="company|company_plot_number|measurement_number|measurement_year|measurement_month|measurement_day|stand_origin|plot_type|stand_type|plot_status|tree_plot_area|tree_plot_shape|tree_tagging_limit|sapling_plot_area|sapling_plot_shape|sapling_tagging_limit_dbh|sapling_tagging_limit_height|regen_plot_area|regen_plot_shape|regen_tagging_limit_conifer|regen_tagging_limit_decid|number_regen_plots|contractor|cruiser_1_name|cruiser_2_name|shrub_cover|herb_forb_cover|grass_cover|moss_lichen_cover|avi_field_call|plot_measurement_comment"; if (!are_headers_valid(headers)) { violations[CSVFILENAME FS "headers" FS  "names" FS "csv headers are invalid" FS "error"]=1; exit 0; } }

action == "validate" && NR > 1 && NF != field_width { log_err("error"); print  NR FS CSVFILENAME FS  FS "invalid-column-count" FS "error" FS  "row " NR " has an invalid column count" FS ""} 
action == "validate:summary" && NR > 1 && NF != field_width { key=CSVFILENAME FS "" FS  "invalid-column-count" FS "row " NR " has an invalid column count" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && company == "" { log_err("error"); print  NR FS CSVFILENAME FS  FS "required" FS "error" FS  "company value is required but was empty" FS "company"} 
action == "validate:summary" && NR > 1 && company == "" { key=CSVFILENAME FS "company" FS  "required" FS "company value is required but was empty" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && company != "" && company !~ /^(AINS|ALPC|ANC|APLY|BLUE|CFPL|CFS|DAIS|FOFP|GOA|HPFP|HLFP|MDFP|MWWC|SFPI|SLPC|SPRA|SUND|TOLK|TOSL|UNKN|UOA|VAND|WFML|WYGP|WYPM)$/ { log_err("error"); print  NR FS CSVFILENAME FS  FS "pattern" FS "error" FS  "company value should match: /^(AINS|ALPC|ANC|APLY|BLUE|CFPL|CFS|DAIS|FOFP|GOA|HPFP|HLFP|MDFP|MWWC|SFPI|SLPC|SPRA|SUND|TOLK|TOSL|UNKN|UOA|VAND|WFML|WYGP|WYPM)$/" FS "company"} 
action == "validate:summary" && NR > 1 && company != "" && company !~ /^(AINS|ALPC|ANC|APLY|BLUE|CFPL|CFS|DAIS|FOFP|GOA|HPFP|HLFP|MDFP|MWWC|SFPI|SLPC|SPRA|SUND|TOLK|TOSL|UNKN|UOA|VAND|WFML|WYGP|WYPM)$/ { key=CSVFILENAME FS "company" FS  "pattern" FS "company value should match: /^(AINS|ALPC|ANC|APLY|BLUE|CFPL|CFS|DAIS|FOFP|GOA|HPFP|HLFP|MDFP|MWWC|SFPI|SLPC|SPRA|SUND|TOLK|TOSL|UNKN|UOA|VAND|WFML|WYGP|WYPM)$/" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && company_plot_number == "" { log_err("error"); print  NR FS CSVFILENAME FS  FS "required" FS "error" FS  "company_plot_number value is required but was empty" FS "company_plot_number"} 
action == "validate:summary" && NR > 1 && company_plot_number == "" { key=CSVFILENAME FS "company_plot_number" FS  "required" FS "company_plot_number value is required but was empty" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && company_plot_number != "" && length(company_plot_number) > 15 { log_err("error"); print  NR FS CSVFILENAME FS  FS "maxLength" FS "error" FS  "company_plot_number max length is: 15" FS "company_plot_number"} 
action == "validate:summary" && NR > 1 && company_plot_number != "" && length(company_plot_number) > 15 { key=CSVFILENAME FS "company_plot_number" FS  "maxLength" FS "company_plot_number max length is: 15" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && measurement_number != "" && !is_integer(measurement_number) { log_err("error"); print  NR FS CSVFILENAME FS  FS "type" FS "error" FS  "measurement_number should be an integer" FS "measurement_number"} 
action == "validate:summary" && NR > 1 && measurement_number != "" && !is_integer(measurement_number) { key=CSVFILENAME FS "measurement_number" FS  "type" FS "measurement_number should be an integer" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && measurement_number == "" { log_err("error"); print  NR FS CSVFILENAME FS  FS "required" FS "error" FS  "measurement_number value is required but was empty" FS "measurement_number"} 
action == "validate:summary" && NR > 1 && measurement_number == "" { key=CSVFILENAME FS "measurement_number" FS  "required" FS "measurement_number value is required but was empty" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && measurement_number != "" && length(measurement_number) > 2 { log_err("error"); print  NR FS CSVFILENAME FS  FS "maxLength" FS "error" FS  "measurement_number max length is: 2" FS "measurement_number"} 
action == "validate:summary" && NR > 1 && measurement_number != "" && length(measurement_number) > 2 { key=CSVFILENAME FS "measurement_number" FS  "maxLength" FS "measurement_number max length is: 2" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && measurement_year != "" && !is_integer(measurement_year) { log_err("error"); print  NR FS CSVFILENAME FS  FS "type" FS "error" FS  "measurement_year should be an integer" FS "measurement_year"} 
action == "validate:summary" && NR > 1 && measurement_year != "" && !is_integer(measurement_year) { key=CSVFILENAME FS "measurement_year" FS  "type" FS "measurement_year should be an integer" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && measurement_year == "" { log_err("error"); print  NR FS CSVFILENAME FS  FS "required" FS "error" FS  "measurement_year value is required but was empty" FS "measurement_year"} 
action == "validate:summary" && NR > 1 && measurement_year == "" { key=CSVFILENAME FS "measurement_year" FS  "required" FS "measurement_year value is required but was empty" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && measurement_year != "" && measurement_year < 1900 { log_err("error"); print  NR FS CSVFILENAME FS  FS "minimum" FS "error" FS  "measurement_year value should be greater or equal to: 1900" FS "measurement_year"} 
action == "validate:summary" && NR > 1 && measurement_year != "" && measurement_year < 1900 { key=CSVFILENAME FS "measurement_year" FS  "minimum" FS "measurement_year value should be greater or equal to: 1900" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && measurement_year != "" && measurement_year > 2050 { log_err("error"); print  NR FS CSVFILENAME FS  FS "maximum" FS "error" FS  "measurement_year value should be less or equal to: 2050" FS "measurement_year"} 
action == "validate:summary" && NR > 1 && measurement_year != "" && measurement_year > 2050 { key=CSVFILENAME FS "measurement_year" FS  "maximum" FS "measurement_year value should be less or equal to: 2050" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && measurement_month != "" && !is_integer(measurement_month) { log_err("error"); print  NR FS CSVFILENAME FS  FS "type" FS "error" FS  "measurement_month should be an integer" FS "measurement_month"} 
action == "validate:summary" && NR > 1 && measurement_month != "" && !is_integer(measurement_month) { key=CSVFILENAME FS "measurement_month" FS  "type" FS "measurement_month should be an integer" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && measurement_month == "" { log_err("warning"); print  NR FS CSVFILENAME FS  FS "required" FS "warning" FS  "measurement_month value is required but was empty" FS "measurement_month"} 
action == "validate:summary" && NR > 1 && measurement_month == "" { key=CSVFILENAME FS "measurement_month" FS  "required" FS "measurement_month value is required but was empty" FS "warning"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && measurement_month != "" && measurement_month < 1 { log_err("error"); print  NR FS CSVFILENAME FS  FS "minimum" FS "error" FS  "measurement_month value should be greater or equal to: 1" FS "measurement_month"} 
action == "validate:summary" && NR > 1 && measurement_month != "" && measurement_month < 1 { key=CSVFILENAME FS "measurement_month" FS  "minimum" FS "measurement_month value should be greater or equal to: 1" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && measurement_month != "" && measurement_month > 12 { log_err("error"); print  NR FS CSVFILENAME FS  FS "maximum" FS "error" FS  "measurement_month value should be less or equal to: 12" FS "measurement_month"} 
action == "validate:summary" && NR > 1 && measurement_month != "" && measurement_month > 12 { key=CSVFILENAME FS "measurement_month" FS  "maximum" FS "measurement_month value should be less or equal to: 12" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && measurement_day != "" && !is_integer(measurement_day) { log_err("error"); print  NR FS CSVFILENAME FS  FS "type" FS "error" FS  "measurement_day should be an integer" FS "measurement_day"} 
action == "validate:summary" && NR > 1 && measurement_day != "" && !is_integer(measurement_day) { key=CSVFILENAME FS "measurement_day" FS  "type" FS "measurement_day should be an integer" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && measurement_day == "" { log_err("warning"); print  NR FS CSVFILENAME FS  FS "required" FS "warning" FS  "measurement_day value is required but was empty" FS "measurement_day"} 
action == "validate:summary" && NR > 1 && measurement_day == "" { key=CSVFILENAME FS "measurement_day" FS  "required" FS "measurement_day value is required but was empty" FS "warning"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && measurement_day != "" && measurement_day < 1 { log_err("error"); print  NR FS CSVFILENAME FS  FS "minimum" FS "error" FS  "measurement_day value should be greater or equal to: 1" FS "measurement_day"} 
action == "validate:summary" && NR > 1 && measurement_day != "" && measurement_day < 1 { key=CSVFILENAME FS "measurement_day" FS  "minimum" FS "measurement_day value should be greater or equal to: 1" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && measurement_day != "" && measurement_day > 31 { log_err("error"); print  NR FS CSVFILENAME FS  FS "maximum" FS "error" FS  "measurement_day value should be less or equal to: 31" FS "measurement_day"} 
action == "validate:summary" && NR > 1 && measurement_day != "" && measurement_day > 31 { key=CSVFILENAME FS "measurement_day" FS  "maximum" FS "measurement_day value should be less or equal to: 31" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && stand_origin == "" { log_err("error"); print  NR FS CSVFILENAME FS  FS "required" FS "error" FS  "stand_origin value is required but was empty" FS "stand_origin"} 
action == "validate:summary" && NR > 1 && stand_origin == "" { key=CSVFILENAME FS "stand_origin" FS  "required" FS "stand_origin value is required but was empty" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && stand_origin != "" && stand_origin !~ /^(A|B|C|F|L|N|P|R|S)$/ { log_err("error"); print  NR FS CSVFILENAME FS  FS "pattern" FS "error" FS  "stand_origin value should match: /^(A|B|C|F|L|N|P|R|S)$/" FS "stand_origin"} 
action == "validate:summary" && NR > 1 && stand_origin != "" && stand_origin !~ /^(A|B|C|F|L|N|P|R|S)$/ { key=CSVFILENAME FS "stand_origin" FS  "pattern" FS "stand_origin value should match: /^(A|B|C|F|L|N|P|R|S)$/" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && plot_type != "" && !is_integer(plot_type) { log_err("error"); print  NR FS CSVFILENAME FS  FS "type" FS "error" FS  "plot_type should be an integer" FS "plot_type"} 
action == "validate:summary" && NR > 1 && plot_type != "" && !is_integer(plot_type) { key=CSVFILENAME FS "plot_type" FS  "type" FS "plot_type should be an integer" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && plot_type == "" { log_err("error"); print  NR FS CSVFILENAME FS  FS "required" FS "error" FS  "plot_type value is required but was empty" FS "plot_type"} 
action == "validate:summary" && NR > 1 && plot_type == "" { key=CSVFILENAME FS "plot_type" FS  "required" FS "plot_type value is required but was empty" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && plot_type != "" && plot_type !~ /^(1|2|3|4)$/ { log_err("error"); print  NR FS CSVFILENAME FS  FS "pattern" FS "error" FS  "plot_type value should match: /^(1|2|3|4)$/" FS "plot_type"} 
action == "validate:summary" && NR > 1 && plot_type != "" && plot_type !~ /^(1|2|3|4)$/ { key=CSVFILENAME FS "plot_type" FS  "pattern" FS "plot_type value should match: /^(1|2|3|4)$/" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && stand_type != "" && !is_integer(stand_type) { log_err("error"); print  NR FS CSVFILENAME FS  FS "type" FS "error" FS  "stand_type should be an integer" FS "stand_type"} 
action == "validate:summary" && NR > 1 && stand_type != "" && !is_integer(stand_type) { key=CSVFILENAME FS "stand_type" FS  "type" FS "stand_type should be an integer" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && stand_type == "" { log_err("error"); print  NR FS CSVFILENAME FS  FS "required" FS "error" FS  "stand_type value is required but was empty" FS "stand_type"} 
action == "validate:summary" && NR > 1 && stand_type == "" { key=CSVFILENAME FS "stand_type" FS  "required" FS "stand_type value is required but was empty" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && stand_type != "" && stand_type !~ /^(1|2|3)$/ { log_err("error"); print  NR FS CSVFILENAME FS  FS "pattern" FS "error" FS  "stand_type value should match: /^(1|2|3)$/" FS "stand_type"} 
action == "validate:summary" && NR > 1 && stand_type != "" && stand_type !~ /^(1|2|3)$/ { key=CSVFILENAME FS "stand_type" FS  "pattern" FS "stand_type value should match: /^(1|2|3)$/" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && plot_status != "" && !is_integer(plot_status) { log_err("error"); print  NR FS CSVFILENAME FS  FS "type" FS "error" FS  "plot_status should be an integer" FS "plot_status"} 
action == "validate:summary" && NR > 1 && plot_status != "" && !is_integer(plot_status) { key=CSVFILENAME FS "plot_status" FS  "type" FS "plot_status should be an integer" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && plot_status == "" { log_err("warning"); print  NR FS CSVFILENAME FS  FS "required" FS "warning" FS  "plot_status value is required but was empty" FS "plot_status"} 
action == "validate:summary" && NR > 1 && plot_status == "" { key=CSVFILENAME FS "plot_status" FS  "required" FS "plot_status value is required but was empty" FS "warning"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && plot_status != "" && plot_status !~ /^(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21)$/ { log_err("error"); print  NR FS CSVFILENAME FS  FS "pattern" FS "error" FS  "plot_status value should match: /^(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21)$/" FS "plot_status"} 
action == "validate:summary" && NR > 1 && plot_status != "" && plot_status !~ /^(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21)$/ { key=CSVFILENAME FS "plot_status" FS  "pattern" FS "plot_status value should match: /^(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21)$/" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && tree_plot_area != "" && !is_number(tree_plot_area) { log_err("error"); print  NR FS CSVFILENAME FS  FS "type" FS "error" FS  "tree_plot_area should be a decimal number" FS "tree_plot_area"} 
action == "validate:summary" && NR > 1 && tree_plot_area != "" && !is_number(tree_plot_area) { key=CSVFILENAME FS "tree_plot_area" FS  "type" FS "tree_plot_area should be a decimal number" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && tree_plot_area == "" { log_err("error"); print  NR FS CSVFILENAME FS  FS "required" FS "error" FS  "tree_plot_area value is required but was empty" FS "tree_plot_area"} 
action == "validate:summary" && NR > 1 && tree_plot_area == "" { key=CSVFILENAME FS "tree_plot_area" FS  "required" FS "tree_plot_area value is required but was empty" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && tree_plot_area != "" && tree_plot_area < 400 { log_err("error"); print  NR FS CSVFILENAME FS  FS "minimum" FS "error" FS  "tree_plot_area value should be greater or equal to: 400" FS "tree_plot_area"} 
action == "validate:summary" && NR > 1 && tree_plot_area != "" && tree_plot_area < 400 { key=CSVFILENAME FS "tree_plot_area" FS  "minimum" FS "tree_plot_area value should be greater or equal to: 400" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && tree_plot_area != "" && tree_plot_area > 2500 { log_err("error"); print  NR FS CSVFILENAME FS  FS "maximum" FS "error" FS  "tree_plot_area value should be less or equal to: 2500" FS "tree_plot_area"} 
action == "validate:summary" && NR > 1 && tree_plot_area != "" && tree_plot_area > 2500 { key=CSVFILENAME FS "tree_plot_area" FS  "maximum" FS "tree_plot_area value should be less or equal to: 2500" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && tree_plot_area != "" && tree_plot_area !~ /^[0-9]*.[0-9]{1}$/ { log_err("error"); print  NR FS CSVFILENAME FS  FS "pattern" FS "error" FS  "tree_plot_area value should match: /^[0-9]*.[0-9]{1}$/" FS "tree_plot_area"} 
action == "validate:summary" && NR > 1 && tree_plot_area != "" && tree_plot_area !~ /^[0-9]*.[0-9]{1}$/ { key=CSVFILENAME FS "tree_plot_area" FS  "pattern" FS "tree_plot_area value should match: /^[0-9]*.[0-9]{1}$/" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && tree_plot_shape == "" { log_err("warning"); print  NR FS CSVFILENAME FS  FS "required" FS "warning" FS  "tree_plot_shape value is required but was empty" FS "tree_plot_shape"} 
action == "validate:summary" && NR > 1 && tree_plot_shape == "" { key=CSVFILENAME FS "tree_plot_shape" FS  "required" FS "tree_plot_shape value is required but was empty" FS "warning"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && tree_plot_shape != "" && tree_plot_shape !~ /^(C|R|S)$/ { log_err("error"); print  NR FS CSVFILENAME FS  FS "pattern" FS "error" FS  "tree_plot_shape value should match: /^(C|R|S)$/" FS "tree_plot_shape"} 
action == "validate:summary" && NR > 1 && tree_plot_shape != "" && tree_plot_shape !~ /^(C|R|S)$/ { key=CSVFILENAME FS "tree_plot_shape" FS  "pattern" FS "tree_plot_shape value should match: /^(C|R|S)$/" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && tree_tagging_limit != "" && !is_number(tree_tagging_limit) { log_err("error"); print  NR FS CSVFILENAME FS  FS "type" FS "error" FS  "tree_tagging_limit should be a decimal number" FS "tree_tagging_limit"} 
action == "validate:summary" && NR > 1 && tree_tagging_limit != "" && !is_number(tree_tagging_limit) { key=CSVFILENAME FS "tree_tagging_limit" FS  "type" FS "tree_tagging_limit should be a decimal number" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && tree_tagging_limit == "" { log_err("error"); print  NR FS CSVFILENAME FS  FS "required" FS "error" FS  "tree_tagging_limit value is required but was empty" FS "tree_tagging_limit"} 
action == "validate:summary" && NR > 1 && tree_tagging_limit == "" { key=CSVFILENAME FS "tree_tagging_limit" FS  "required" FS "tree_tagging_limit value is required but was empty" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && tree_tagging_limit != "" && tree_tagging_limit < 0.1 { log_err("error"); print  NR FS CSVFILENAME FS  FS "minimum" FS "error" FS  "tree_tagging_limit value should be greater or equal to: 0.1" FS "tree_tagging_limit"} 
action == "validate:summary" && NR > 1 && tree_tagging_limit != "" && tree_tagging_limit < 0.1 { key=CSVFILENAME FS "tree_tagging_limit" FS  "minimum" FS "tree_tagging_limit value should be greater or equal to: 0.1" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && tree_tagging_limit != "" && tree_tagging_limit > 9.1 { log_err("error"); print  NR FS CSVFILENAME FS  FS "maximum" FS "error" FS  "tree_tagging_limit value should be less or equal to: 9.1" FS "tree_tagging_limit"} 
action == "validate:summary" && NR > 1 && tree_tagging_limit != "" && tree_tagging_limit > 9.1 { key=CSVFILENAME FS "tree_tagging_limit" FS  "maximum" FS "tree_tagging_limit value should be less or equal to: 9.1" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && tree_tagging_limit != "" && tree_tagging_limit !~ /^[0-9].[0-9]{1}$/ { log_err("error"); print  NR FS CSVFILENAME FS  FS "pattern" FS "error" FS  "tree_tagging_limit value should match: /^[0-9].[0-9]{1}$/" FS "tree_tagging_limit"} 
action == "validate:summary" && NR > 1 && tree_tagging_limit != "" && tree_tagging_limit !~ /^[0-9].[0-9]{1}$/ { key=CSVFILENAME FS "tree_tagging_limit" FS  "pattern" FS "tree_tagging_limit value should match: /^[0-9].[0-9]{1}$/" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && sapling_plot_area != "" && !is_number(sapling_plot_area) { log_err("error"); print  NR FS CSVFILENAME FS  FS "type" FS "error" FS  "sapling_plot_area should be a decimal number" FS "sapling_plot_area"} 
action == "validate:summary" && NR > 1 && sapling_plot_area != "" && !is_number(sapling_plot_area) { key=CSVFILENAME FS "sapling_plot_area" FS  "type" FS "sapling_plot_area should be a decimal number" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && sapling_plot_area == "" { log_err("error"); print  NR FS CSVFILENAME FS  FS "required" FS "error" FS  "sapling_plot_area value is required but was empty" FS "sapling_plot_area"} 
action == "validate:summary" && NR > 1 && sapling_plot_area == "" { key=CSVFILENAME FS "sapling_plot_area" FS  "required" FS "sapling_plot_area value is required but was empty" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && sapling_plot_area != "" && sapling_plot_area < 0 { log_err("error"); print  NR FS CSVFILENAME FS  FS "minimum" FS "error" FS  "sapling_plot_area value should be greater or equal to: 0" FS "sapling_plot_area"} 
action == "validate:summary" && NR > 1 && sapling_plot_area != "" && sapling_plot_area < 0 { key=CSVFILENAME FS "sapling_plot_area" FS  "minimum" FS "sapling_plot_area value should be greater or equal to: 0" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && sapling_plot_area != "" && sapling_plot_area > 2500 { log_err("error"); print  NR FS CSVFILENAME FS  FS "maximum" FS "error" FS  "sapling_plot_area value should be less or equal to: 2500" FS "sapling_plot_area"} 
action == "validate:summary" && NR > 1 && sapling_plot_area != "" && sapling_plot_area > 2500 { key=CSVFILENAME FS "sapling_plot_area" FS  "maximum" FS "sapling_plot_area value should be less or equal to: 2500" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && sapling_plot_area != "" && sapling_plot_area !~ /^[0-9]*.[0-9]{1}$/ { log_err("error"); print  NR FS CSVFILENAME FS  FS "pattern" FS "error" FS  "sapling_plot_area value should match: /^[0-9]*.[0-9]{1}$/" FS "sapling_plot_area"} 
action == "validate:summary" && NR > 1 && sapling_plot_area != "" && sapling_plot_area !~ /^[0-9]*.[0-9]{1}$/ { key=CSVFILENAME FS "sapling_plot_area" FS  "pattern" FS "sapling_plot_area value should match: /^[0-9]*.[0-9]{1}$/" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && sapling_plot_shape == "" { log_err("warning"); print  NR FS CSVFILENAME FS  FS "required" FS "warning" FS  "sapling_plot_shape value is required but was empty" FS "sapling_plot_shape"} 
action == "validate:summary" && NR > 1 && sapling_plot_shape == "" { key=CSVFILENAME FS "sapling_plot_shape" FS  "required" FS "sapling_plot_shape value is required but was empty" FS "warning"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && sapling_plot_shape != "" && sapling_plot_shape !~ /^(C|R|S)$/ { log_err("error"); print  NR FS CSVFILENAME FS  FS "pattern" FS "error" FS  "sapling_plot_shape value should match: /^(C|R|S)$/" FS "sapling_plot_shape"} 
action == "validate:summary" && NR > 1 && sapling_plot_shape != "" && sapling_plot_shape !~ /^(C|R|S)$/ { key=CSVFILENAME FS "sapling_plot_shape" FS  "pattern" FS "sapling_plot_shape value should match: /^(C|R|S)$/" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && sapling_tagging_limit_dbh != "" && !is_number(sapling_tagging_limit_dbh) { log_err("error"); print  NR FS CSVFILENAME FS  FS "type" FS "error" FS  "sapling_tagging_limit_dbh should be a decimal number" FS "sapling_tagging_limit_dbh"} 
action == "validate:summary" && NR > 1 && sapling_tagging_limit_dbh != "" && !is_number(sapling_tagging_limit_dbh) { key=CSVFILENAME FS "sapling_tagging_limit_dbh" FS  "type" FS "sapling_tagging_limit_dbh should be a decimal number" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && sapling_tagging_limit_dbh != "" && sapling_tagging_limit_dbh < 0.1 { log_err("error"); print  NR FS CSVFILENAME FS  FS "minimum" FS "error" FS  "sapling_tagging_limit_dbh value should be greater or equal to: 0.1" FS "sapling_tagging_limit_dbh"} 
action == "validate:summary" && NR > 1 && sapling_tagging_limit_dbh != "" && sapling_tagging_limit_dbh < 0.1 { key=CSVFILENAME FS "sapling_tagging_limit_dbh" FS  "minimum" FS "sapling_tagging_limit_dbh value should be greater or equal to: 0.1" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && sapling_tagging_limit_dbh != "" && sapling_tagging_limit_dbh > 9.1 { log_err("error"); print  NR FS CSVFILENAME FS  FS "maximum" FS "error" FS  "sapling_tagging_limit_dbh value should be less or equal to: 9.1" FS "sapling_tagging_limit_dbh"} 
action == "validate:summary" && NR > 1 && sapling_tagging_limit_dbh != "" && sapling_tagging_limit_dbh > 9.1 { key=CSVFILENAME FS "sapling_tagging_limit_dbh" FS  "maximum" FS "sapling_tagging_limit_dbh value should be less or equal to: 9.1" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && sapling_tagging_limit_dbh != "" && sapling_tagging_limit_dbh !~ /^[0-9].[0-9]{1}$/ { log_err("error"); print  NR FS CSVFILENAME FS  FS "pattern" FS "error" FS  "sapling_tagging_limit_dbh value should match: /^[0-9].[0-9]{1}$/" FS "sapling_tagging_limit_dbh"} 
action == "validate:summary" && NR > 1 && sapling_tagging_limit_dbh != "" && sapling_tagging_limit_dbh !~ /^[0-9].[0-9]{1}$/ { key=CSVFILENAME FS "sapling_tagging_limit_dbh" FS  "pattern" FS "sapling_tagging_limit_dbh value should match: /^[0-9].[0-9]{1}$/" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && sapling_tagging_limit_height != "" && !is_number(sapling_tagging_limit_height) { log_err("error"); print  NR FS CSVFILENAME FS  FS "type" FS "error" FS  "sapling_tagging_limit_height should be a decimal number" FS "sapling_tagging_limit_height"} 
action == "validate:summary" && NR > 1 && sapling_tagging_limit_height != "" && !is_number(sapling_tagging_limit_height) { key=CSVFILENAME FS "sapling_tagging_limit_height" FS  "type" FS "sapling_tagging_limit_height should be a decimal number" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && sapling_tagging_limit_height != "" && sapling_tagging_limit_height < 1.3 { log_err("error"); print  NR FS CSVFILENAME FS  FS "minimum" FS "error" FS  "sapling_tagging_limit_height value should be greater or equal to: 1.3" FS "sapling_tagging_limit_height"} 
action == "validate:summary" && NR > 1 && sapling_tagging_limit_height != "" && sapling_tagging_limit_height < 1.3 { key=CSVFILENAME FS "sapling_tagging_limit_height" FS  "minimum" FS "sapling_tagging_limit_height value should be greater or equal to: 1.3" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && sapling_tagging_limit_height != "" && sapling_tagging_limit_height > 1.5 { log_err("error"); print  NR FS CSVFILENAME FS  FS "maximum" FS "error" FS  "sapling_tagging_limit_height value should be less or equal to: 1.5" FS "sapling_tagging_limit_height"} 
action == "validate:summary" && NR > 1 && sapling_tagging_limit_height != "" && sapling_tagging_limit_height > 1.5 { key=CSVFILENAME FS "sapling_tagging_limit_height" FS  "maximum" FS "sapling_tagging_limit_height value should be less or equal to: 1.5" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && sapling_tagging_limit_height != "" && sapling_tagging_limit_height !~ /^[0-9].[0-9]{2}$/ { log_err("error"); print  NR FS CSVFILENAME FS  FS "pattern" FS "error" FS  "sapling_tagging_limit_height value should match: /^[0-9].[0-9]{2}$/" FS "sapling_tagging_limit_height"} 
action == "validate:summary" && NR > 1 && sapling_tagging_limit_height != "" && sapling_tagging_limit_height !~ /^[0-9].[0-9]{2}$/ { key=CSVFILENAME FS "sapling_tagging_limit_height" FS  "pattern" FS "sapling_tagging_limit_height value should match: /^[0-9].[0-9]{2}$/" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && regen_plot_area != "" && !is_number(regen_plot_area) { log_err("error"); print  NR FS CSVFILENAME FS  FS "type" FS "error" FS  "regen_plot_area should be a decimal number" FS "regen_plot_area"} 
action == "validate:summary" && NR > 1 && regen_plot_area != "" && !is_number(regen_plot_area) { key=CSVFILENAME FS "regen_plot_area" FS  "type" FS "regen_plot_area should be a decimal number" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && regen_plot_area == "" { log_err("error"); print  NR FS CSVFILENAME FS  FS "required" FS "error" FS  "regen_plot_area value is required but was empty" FS "regen_plot_area"} 
action == "validate:summary" && NR > 1 && regen_plot_area == "" { key=CSVFILENAME FS "regen_plot_area" FS  "required" FS "regen_plot_area value is required but was empty" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && regen_plot_area != "" && regen_plot_area < 0 { log_err("error"); print  NR FS CSVFILENAME FS  FS "minimum" FS "error" FS  "regen_plot_area value should be greater or equal to: 0" FS "regen_plot_area"} 
action == "validate:summary" && NR > 1 && regen_plot_area != "" && regen_plot_area < 0 { key=CSVFILENAME FS "regen_plot_area" FS  "minimum" FS "regen_plot_area value should be greater or equal to: 0" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && regen_plot_area != "" && regen_plot_area > 2500 { log_err("error"); print  NR FS CSVFILENAME FS  FS "maximum" FS "error" FS  "regen_plot_area value should be less or equal to: 2500" FS "regen_plot_area"} 
action == "validate:summary" && NR > 1 && regen_plot_area != "" && regen_plot_area > 2500 { key=CSVFILENAME FS "regen_plot_area" FS  "maximum" FS "regen_plot_area value should be less or equal to: 2500" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && regen_plot_area != "" && regen_plot_area !~ /^[0-9]*.[0-9]{1}$/ { log_err("error"); print  NR FS CSVFILENAME FS  FS "pattern" FS "error" FS  "regen_plot_area value should match: /^[0-9]*.[0-9]{1}$/" FS "regen_plot_area"} 
action == "validate:summary" && NR > 1 && regen_plot_area != "" && regen_plot_area !~ /^[0-9]*.[0-9]{1}$/ { key=CSVFILENAME FS "regen_plot_area" FS  "pattern" FS "regen_plot_area value should match: /^[0-9]*.[0-9]{1}$/" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && regen_plot_shape == "" { log_err("warning"); print  NR FS CSVFILENAME FS  FS "required" FS "warning" FS  "regen_plot_shape value is required but was empty" FS "regen_plot_shape"} 
action == "validate:summary" && NR > 1 && regen_plot_shape == "" { key=CSVFILENAME FS "regen_plot_shape" FS  "required" FS "regen_plot_shape value is required but was empty" FS "warning"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && regen_plot_shape != "" && regen_plot_shape !~ /^(C|R|S)$/ { log_err("error"); print  NR FS CSVFILENAME FS  FS "pattern" FS "error" FS  "regen_plot_shape value should match: /^(C|R|S)$/" FS "regen_plot_shape"} 
action == "validate:summary" && NR > 1 && regen_plot_shape != "" && regen_plot_shape !~ /^(C|R|S)$/ { key=CSVFILENAME FS "regen_plot_shape" FS  "pattern" FS "regen_plot_shape value should match: /^(C|R|S)$/" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && regen_tagging_limit_conifer != "" && !is_number(regen_tagging_limit_conifer) { log_err("error"); print  NR FS CSVFILENAME FS  FS "type" FS "error" FS  "regen_tagging_limit_conifer should be a decimal number" FS "regen_tagging_limit_conifer"} 
action == "validate:summary" && NR > 1 && regen_tagging_limit_conifer != "" && !is_number(regen_tagging_limit_conifer) { key=CSVFILENAME FS "regen_tagging_limit_conifer" FS  "type" FS "regen_tagging_limit_conifer should be a decimal number" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && regen_tagging_limit_conifer != "" && regen_tagging_limit_conifer < 0.1 { log_err("error"); print  NR FS CSVFILENAME FS  FS "minimum" FS "error" FS  "regen_tagging_limit_conifer value should be greater or equal to: 0.1" FS "regen_tagging_limit_conifer"} 
action == "validate:summary" && NR > 1 && regen_tagging_limit_conifer != "" && regen_tagging_limit_conifer < 0.1 { key=CSVFILENAME FS "regen_tagging_limit_conifer" FS  "minimum" FS "regen_tagging_limit_conifer value should be greater or equal to: 0.1" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && regen_tagging_limit_conifer != "" && regen_tagging_limit_conifer > 1.3 { log_err("error"); print  NR FS CSVFILENAME FS  FS "maximum" FS "error" FS  "regen_tagging_limit_conifer value should be less or equal to: 1.3" FS "regen_tagging_limit_conifer"} 
action == "validate:summary" && NR > 1 && regen_tagging_limit_conifer != "" && regen_tagging_limit_conifer > 1.3 { key=CSVFILENAME FS "regen_tagging_limit_conifer" FS  "maximum" FS "regen_tagging_limit_conifer value should be less or equal to: 1.3" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && regen_tagging_limit_conifer != "" && regen_tagging_limit_conifer !~ /^[0-9].[0-9]{2}$/ { log_err("error"); print  NR FS CSVFILENAME FS  FS "pattern" FS "error" FS  "regen_tagging_limit_conifer value should match: /^[0-9].[0-9]{2}$/" FS "regen_tagging_limit_conifer"} 
action == "validate:summary" && NR > 1 && regen_tagging_limit_conifer != "" && regen_tagging_limit_conifer !~ /^[0-9].[0-9]{2}$/ { key=CSVFILENAME FS "regen_tagging_limit_conifer" FS  "pattern" FS "regen_tagging_limit_conifer value should match: /^[0-9].[0-9]{2}$/" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && regen_tagging_limit_decid != "" && !is_number(regen_tagging_limit_decid) { log_err("error"); print  NR FS CSVFILENAME FS  FS "type" FS "error" FS  "regen_tagging_limit_decid should be a decimal number" FS "regen_tagging_limit_decid"} 
action == "validate:summary" && NR > 1 && regen_tagging_limit_decid != "" && !is_number(regen_tagging_limit_decid) { key=CSVFILENAME FS "regen_tagging_limit_decid" FS  "type" FS "regen_tagging_limit_decid should be a decimal number" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && regen_tagging_limit_decid != "" && regen_tagging_limit_decid < 0.1 { log_err("error"); print  NR FS CSVFILENAME FS  FS "minimum" FS "error" FS  "regen_tagging_limit_decid value should be greater or equal to: 0.1" FS "regen_tagging_limit_decid"} 
action == "validate:summary" && NR > 1 && regen_tagging_limit_decid != "" && regen_tagging_limit_decid < 0.1 { key=CSVFILENAME FS "regen_tagging_limit_decid" FS  "minimum" FS "regen_tagging_limit_decid value should be greater or equal to: 0.1" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && regen_tagging_limit_decid != "" && regen_tagging_limit_decid > 1.3 { log_err("error"); print  NR FS CSVFILENAME FS  FS "maximum" FS "error" FS  "regen_tagging_limit_decid value should be less or equal to: 1.3" FS "regen_tagging_limit_decid"} 
action == "validate:summary" && NR > 1 && regen_tagging_limit_decid != "" && regen_tagging_limit_decid > 1.3 { key=CSVFILENAME FS "regen_tagging_limit_decid" FS  "maximum" FS "regen_tagging_limit_decid value should be less or equal to: 1.3" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && regen_tagging_limit_decid != "" && regen_tagging_limit_decid !~ /^[0-9].[0-9]{2}$/ { log_err("error"); print  NR FS CSVFILENAME FS  FS "pattern" FS "error" FS  "regen_tagging_limit_decid value should match: /^[0-9].[0-9]{2}$/" FS "regen_tagging_limit_decid"} 
action == "validate:summary" && NR > 1 && regen_tagging_limit_decid != "" && regen_tagging_limit_decid !~ /^[0-9].[0-9]{2}$/ { key=CSVFILENAME FS "regen_tagging_limit_decid" FS  "pattern" FS "regen_tagging_limit_decid value should match: /^[0-9].[0-9]{2}$/" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && number_regen_plots != "" && !is_integer(number_regen_plots) { log_err("error"); print  NR FS CSVFILENAME FS  FS "type" FS "error" FS  "number_regen_plots should be an integer" FS "number_regen_plots"} 
action == "validate:summary" && NR > 1 && number_regen_plots != "" && !is_integer(number_regen_plots) { key=CSVFILENAME FS "number_regen_plots" FS  "type" FS "number_regen_plots should be an integer" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && number_regen_plots == "" { log_err("error"); print  NR FS CSVFILENAME FS  FS "required" FS "error" FS  "number_regen_plots value is required but was empty" FS "number_regen_plots"} 
action == "validate:summary" && NR > 1 && number_regen_plots == "" { key=CSVFILENAME FS "number_regen_plots" FS  "required" FS "number_regen_plots value is required but was empty" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && number_regen_plots != "" && number_regen_plots < 0 { log_err("error"); print  NR FS CSVFILENAME FS  FS "minimum" FS "error" FS  "number_regen_plots value should be greater or equal to: 0" FS "number_regen_plots"} 
action == "validate:summary" && NR > 1 && number_regen_plots != "" && number_regen_plots < 0 { key=CSVFILENAME FS "number_regen_plots" FS  "minimum" FS "number_regen_plots value should be greater or equal to: 0" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && number_regen_plots != "" && number_regen_plots > 10 { log_err("error"); print  NR FS CSVFILENAME FS  FS "maximum" FS "error" FS  "number_regen_plots value should be less or equal to: 10" FS "number_regen_plots"} 
action == "validate:summary" && NR > 1 && number_regen_plots != "" && number_regen_plots > 10 { key=CSVFILENAME FS "number_regen_plots" FS  "maximum" FS "number_regen_plots value should be less or equal to: 10" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && contractor != "" && length(contractor) > 50 { log_err("error"); print  NR FS CSVFILENAME FS  FS "maxLength" FS "error" FS  "contractor max length is: 50" FS "contractor"} 
action == "validate:summary" && NR > 1 && contractor != "" && length(contractor) > 50 { key=CSVFILENAME FS "contractor" FS  "maxLength" FS "contractor max length is: 50" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && cruiser_1_name != "" && length(cruiser_1_name) > 25 { log_err("error"); print  NR FS CSVFILENAME FS  FS "maxLength" FS "error" FS  "cruiser_1_name max length is: 25" FS "cruiser_1_name"} 
action == "validate:summary" && NR > 1 && cruiser_1_name != "" && length(cruiser_1_name) > 25 { key=CSVFILENAME FS "cruiser_1_name" FS  "maxLength" FS "cruiser_1_name max length is: 25" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && cruiser_2_name != "" && length(cruiser_2_name) > 25 { log_err("error"); print  NR FS CSVFILENAME FS  FS "maxLength" FS "error" FS  "cruiser_2_name max length is: 25" FS "cruiser_2_name"} 
action == "validate:summary" && NR > 1 && cruiser_2_name != "" && length(cruiser_2_name) > 25 { key=CSVFILENAME FS "cruiser_2_name" FS  "maxLength" FS "cruiser_2_name max length is: 25" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && shrub_cover != "" && !is_integer(shrub_cover) { log_err("error"); print  NR FS CSVFILENAME FS  FS "type" FS "error" FS  "shrub_cover should be an integer" FS "shrub_cover"} 
action == "validate:summary" && NR > 1 && shrub_cover != "" && !is_integer(shrub_cover) { key=CSVFILENAME FS "shrub_cover" FS  "type" FS "shrub_cover should be an integer" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && shrub_cover == "" { log_err("warning"); print  NR FS CSVFILENAME FS  FS "required" FS "warning" FS  "shrub_cover value is required but was empty" FS "shrub_cover"} 
action == "validate:summary" && NR > 1 && shrub_cover == "" { key=CSVFILENAME FS "shrub_cover" FS  "required" FS "shrub_cover value is required but was empty" FS "warning"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && shrub_cover != "" && shrub_cover !~ /^(0|5|10|15|20|25|30|35|40|45|50|55|60|65|70|75|80|85|90|95|100)$/ { log_err("error"); print  NR FS CSVFILENAME FS  FS "pattern" FS "error" FS  "shrub_cover value should match: /^(0|5|10|15|20|25|30|35|40|45|50|55|60|65|70|75|80|85|90|95|100)$/" FS "shrub_cover"} 
action == "validate:summary" && NR > 1 && shrub_cover != "" && shrub_cover !~ /^(0|5|10|15|20|25|30|35|40|45|50|55|60|65|70|75|80|85|90|95|100)$/ { key=CSVFILENAME FS "shrub_cover" FS  "pattern" FS "shrub_cover value should match: /^(0|5|10|15|20|25|30|35|40|45|50|55|60|65|70|75|80|85|90|95|100)$/" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && herb_forb_cover != "" && !is_integer(herb_forb_cover) { log_err("error"); print  NR FS CSVFILENAME FS  FS "type" FS "error" FS  "herb_forb_cover should be an integer" FS "herb_forb_cover"} 
action == "validate:summary" && NR > 1 && herb_forb_cover != "" && !is_integer(herb_forb_cover) { key=CSVFILENAME FS "herb_forb_cover" FS  "type" FS "herb_forb_cover should be an integer" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && herb_forb_cover == "" { log_err("warning"); print  NR FS CSVFILENAME FS  FS "required" FS "warning" FS  "herb_forb_cover value is required but was empty" FS "herb_forb_cover"} 
action == "validate:summary" && NR > 1 && herb_forb_cover == "" { key=CSVFILENAME FS "herb_forb_cover" FS  "required" FS "herb_forb_cover value is required but was empty" FS "warning"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && herb_forb_cover != "" && herb_forb_cover !~ /^(0|5|10|15|20|25|30|35|40|45|50|55|60|65|70|75|80|85|90|95|100)$/ { log_err("error"); print  NR FS CSVFILENAME FS  FS "pattern" FS "error" FS  "herb_forb_cover value should match: /^(0|5|10|15|20|25|30|35|40|45|50|55|60|65|70|75|80|85|90|95|100)$/" FS "herb_forb_cover"} 
action == "validate:summary" && NR > 1 && herb_forb_cover != "" && herb_forb_cover !~ /^(0|5|10|15|20|25|30|35|40|45|50|55|60|65|70|75|80|85|90|95|100)$/ { key=CSVFILENAME FS "herb_forb_cover" FS  "pattern" FS "herb_forb_cover value should match: /^(0|5|10|15|20|25|30|35|40|45|50|55|60|65|70|75|80|85|90|95|100)$/" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && grass_cover != "" && !is_integer(grass_cover) { log_err("error"); print  NR FS CSVFILENAME FS  FS "type" FS "error" FS  "grass_cover should be an integer" FS "grass_cover"} 
action == "validate:summary" && NR > 1 && grass_cover != "" && !is_integer(grass_cover) { key=CSVFILENAME FS "grass_cover" FS  "type" FS "grass_cover should be an integer" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && grass_cover == "" { log_err("warning"); print  NR FS CSVFILENAME FS  FS "required" FS "warning" FS  "grass_cover value is required but was empty" FS "grass_cover"} 
action == "validate:summary" && NR > 1 && grass_cover == "" { key=CSVFILENAME FS "grass_cover" FS  "required" FS "grass_cover value is required but was empty" FS "warning"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && grass_cover != "" && grass_cover !~ /^(0|5|10|15|20|25|30|35|40|45|50|55|60|65|70|75|80|85|90|95|100)$/ { log_err("error"); print  NR FS CSVFILENAME FS  FS "pattern" FS "error" FS  "grass_cover value should match: /^(0|5|10|15|20|25|30|35|40|45|50|55|60|65|70|75|80|85|90|95|100)$/" FS "grass_cover"} 
action == "validate:summary" && NR > 1 && grass_cover != "" && grass_cover !~ /^(0|5|10|15|20|25|30|35|40|45|50|55|60|65|70|75|80|85|90|95|100)$/ { key=CSVFILENAME FS "grass_cover" FS  "pattern" FS "grass_cover value should match: /^(0|5|10|15|20|25|30|35|40|45|50|55|60|65|70|75|80|85|90|95|100)$/" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && moss_lichen_cover != "" && !is_integer(moss_lichen_cover) { log_err("error"); print  NR FS CSVFILENAME FS  FS "type" FS "error" FS  "moss_lichen_cover should be an integer" FS "moss_lichen_cover"} 
action == "validate:summary" && NR > 1 && moss_lichen_cover != "" && !is_integer(moss_lichen_cover) { key=CSVFILENAME FS "moss_lichen_cover" FS  "type" FS "moss_lichen_cover should be an integer" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && moss_lichen_cover == "" { log_err("warning"); print  NR FS CSVFILENAME FS  FS "required" FS "warning" FS  "moss_lichen_cover value is required but was empty" FS "moss_lichen_cover"} 
action == "validate:summary" && NR > 1 && moss_lichen_cover == "" { key=CSVFILENAME FS "moss_lichen_cover" FS  "required" FS "moss_lichen_cover value is required but was empty" FS "warning"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && moss_lichen_cover != "" && moss_lichen_cover !~ /^(0|5|10|15|20|25|30|35|40|45|50|55|60|65|70|75|80|85|90|95|100)$/ { log_err("error"); print  NR FS CSVFILENAME FS  FS "pattern" FS "error" FS  "moss_lichen_cover value should match: /^(0|5|10|15|20|25|30|35|40|45|50|55|60|65|70|75|80|85|90|95|100)$/" FS "moss_lichen_cover"} 
action == "validate:summary" && NR > 1 && moss_lichen_cover != "" && moss_lichen_cover !~ /^(0|5|10|15|20|25|30|35|40|45|50|55|60|65|70|75|80|85|90|95|100)$/ { key=CSVFILENAME FS "moss_lichen_cover" FS  "pattern" FS "moss_lichen_cover value should match: /^(0|5|10|15|20|25|30|35|40|45|50|55|60|65|70|75|80|85|90|95|100)$/" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && avi_field_call == "" { log_err("warning"); print  NR FS CSVFILENAME FS  FS "required" FS "warning" FS  "avi_field_call value is required but was empty" FS "avi_field_call"} 
action == "validate:summary" && NR > 1 && avi_field_call == "" { key=CSVFILENAME FS "avi_field_call" FS  "required" FS "avi_field_call value is required but was empty" FS "warning"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && avi_field_call != "" && length(avi_field_call) > 80 { log_err("error"); print  NR FS CSVFILENAME FS  FS "maxLength" FS "error" FS  "avi_field_call max length is: 80" FS "avi_field_call"} 
action == "validate:summary" && NR > 1 && avi_field_call != "" && length(avi_field_call) > 80 { key=CSVFILENAME FS "avi_field_call" FS  "maxLength" FS "avi_field_call max length is: 80" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && plot_measurement_comment != "" && length(plot_measurement_comment) > 250 { log_err("error"); print  NR FS CSVFILENAME FS  FS "maxLength" FS "error" FS  "plot_measurement_comment max length is: 250" FS "plot_measurement_comment"} 
action == "validate:summary" && NR > 1 && plot_measurement_comment != "" && length(plot_measurement_comment) > 250 { key=CSVFILENAME FS "plot_measurement_comment" FS  "maxLength" FS "plot_measurement_comment max length is: 250" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 

# sanitize rules
action ~ /^(sanitize|insert)$/ && NR > 1 {
    if (plot_status == "") $10 = "\\N"
    if (measurement_number == "") $3 = "\\N"
    if (regen_plot_area == "") $18 = "\\N"
    if (tree_tagging_limit == "") $13 = "\\N"
    if (contractor == "") $23 = "\\N"
    if (sapling_tagging_limit_height == "") $17 = "\\N"
    if (tree_plot_shape == "") $12 = "\\N"
    if (sapling_plot_shape == "") $15 = "\\N"
    if (sapling_plot_area == "") $14 = "\\N"
    if (tree_plot_area == "") $11 = "\\N"
    if (company_plot_number == "") $2 = "\\N"
    if (regen_tagging_limit_conifer == "") $20 = "\\N"
    if (regen_plot_shape == "") $19 = "\\N"
    if (plot_measurement_comment == "") $31 = "\\N"
    if (grass_cover == "") $28 = "\\N"
    if (cruiser_2_name == "") $25 = "\\N"
    if (number_regen_plots == "") $22 = "\\N"
    if (avi_field_call == "") $30 = "\\N"
    if (herb_forb_cover == "") $27 = "\\N"
    if (moss_lichen_cover == "") $29 = "\\N"
    if (cruiser_1_name == "") $24 = "\\N"
    if (measurement_day == "") $6 = "\\N"
    if (company == "") $1 = "\\N"
    if (shrub_cover == "") $26 = "\\N"
    if (regen_tagging_limit_decid == "") $21 = "\\N"
    if (stand_type == "") $9 = "\\N"
    if (plot_type == "") $8 = "\\N"
    if (sapling_tagging_limit_dbh == "") $16 = "\\N"
    if (stand_origin == "") $7 = "\\N"
    if (measurement_year == "") $4 = "\\N"
    if (measurement_month == "") $5 = "\\N"
}

# action handlers
action == "insert" && NR == 1 {
    print "SET client_encoding = 'UTF8';"
    print "COPY " schema "plot_measurement (" addfields FS "source_row_index" FS $0 ") FROM stdin;"
}
action == "insert" && NR > 1 {
   record = addvals "\t" NR
   for (i = 1; i <= NF; i++) {
       record = record "\t" $i
   }
   print record
}
action == "table" && NR == 1 {
     print "CREATE TABLE IF NOT EXISTS plot_measurement (company ,company_plot_number ,measurement_number ,measurement_year ,measurement_month ,measurement_day ,stand_origin ,plot_type ,stand_type ,plot_status ,tree_plot_area ,tree_plot_shape ,tree_tagging_limit ,sapling_plot_area ,sapling_plot_shape ,sapling_tagging_limit_dbh ,sapling_tagging_limit_height ,regen_plot_area ,regen_plot_shape ,regen_tagging_limit_conifer ,regen_tagging_limit_decid ,number_regen_plots ,contractor ,cruiser_1_name ,cruiser_2_name ,shrub_cover ,herb_forb_cover ,grass_cover ,moss_lichen_cover ,avi_field_call ,plot_measurement_comment );"
}
action == "sanitize" { print }
# la fin
END {
    if (action == "validate:summary" && length(dupkeys) > 0) for (dup in dupkeys) { violation=CSVFILENAME FS "" FS  "duplicate" FS dup " violates pkey" FS "error"; violations[violation] = dupkeys[dup]}
    if (action == "validate:summary") { if (length(violations) > 0) for (violation in violations) { print violation FS violations[violation]; } }
    if (action == "insert") print "\\." RS
    if (action == "validate" && options["summary"] == "true") { print RS "violation summary: " RS "   counts:   " RS "      total: " err_count; print_cats(cats); }
}
