#!/usr/bin/awk -F, -f

# generated by: awk-csvalid https://github.com/tesera/awk-csvalid

# awk-csvalid csv toolset generator: https://github.com/tesera/awk-csvalid
# usage:
#    validate:     awk -f action=validate validator.awk > violations.txt
#    create table: awk -v action=table -f validator.awk | psql afgo_dev
#    sanitize csv: awk -v action=sanitize -f validator.awk > sanitized.csv
#    insert sql:   awk -v action=insert -f validator.awk | psql afgo_dev

# awk is a simple unix text file parser: http://www.gnu.org/software/gawk/manual/gawk.html
# awk primer:
#    NR = number/index current record
#    RS = record seperator new line i.e. \n
#    FS = field seperator i.e. ,
#    /pattern/ { expression } = if pattern is truthy run expression

BEGIN {
    FS=","; OFS=","; err_count=0; cats["na"]=0;
    if(!action) action = "validate"
    summary_header="file_name,field_name,rule,message,violation_count"
    CSVFILENAME = CSVFILENAME ? CSVFILENAME : FILENAME
    FPAT = "([^,]*)|(\"[^\"]+\")"
}

# builtin helper functions
function eql(x,y) {v=1; for (i in x) v=(v&&x[i]==y[i]); return v;}
function are_headers_valid(valid_headers) { v=0; split($0, h, ","); split(valid_headers, vh, "|"); return eql(h, vh); }
function is_unique(i, val) { if (vals[i,val]) { return 0; } else { vals[i,val] = 1; return 1; } }
function is_integer(x) { return x ~ /^-?[0-9]+$/ }
function is_number(x) { return x ~ /^-?[0-9]+.[0-9]+$/ }
function print_cats(categories) { for (category in categories) { if (categories[category]) print "      " category ": " categories[category]; } }
function log_err(cat) { cats[cat]++; err_count++; }


#get rid of the evil windows cr
{ sub("\r$", "") }


{
     for (i = 1; i <= NF; i++) {
         if (substr($i, 1, 1) == "\"") {
             len = length($i)
             $i = substr($i, 2, len - 2)
         }
     }
}


# make header index/map
NR > 1 {
field_width = 28
    company=$1
    company_plot_number=$2
    measurement_number=$3
    tree_number=$4
    tree_type=$5
    dbh=$6
    dbh_height=$7
    rcd=$8
    rcd_height=$9
    height=$10
    crown_class=$11
    dbh_age=$12
    stump_age=$13
    stump_height=$14
    total_age=$15
    htlc=$16
    crown_diameter_ns=$17
    crown_diameter_ew=$18
    condition_code1=$19
    cause1=$20
    severity1=$21
    condition_code2=$22
    cause2=$23
    severity2=$24
    condition_code3=$25
    cause3=$26
    severity3=$27
    trees_measurement_comment=$28
}

# awk rules based on user csv ruleset
NR == 1 && action == "validate" { headers="company|company_plot_number|measurement_number|tree_number|tree_type|dbh|dbh_height|rcd|rcd_height|height|crown_class|dbh_age|stump_age|stump_height|total_age|htlc|crown_diameter_ns|crown_diameter_ew|condition_code1|cause1|severity1|condition_code2|cause2|severity2|condition_code3|cause3|severity3|trees_measurement_comment"; if (!are_headers_valid(headers)) { gsub(/\|/, FS, headers); print  NR FS CSVFILENAME FS "header" FS "invalid-header" FS "error" FS  "headers are invalid "; exit 0;} }
NR == 1 && action == "validate:summary" { headers="company|company_plot_number|measurement_number|tree_number|tree_type|dbh|dbh_height|rcd|rcd_height|height|crown_class|dbh_age|stump_age|stump_height|total_age|htlc|crown_diameter_ns|crown_diameter_ew|condition_code1|cause1|severity1|condition_code2|cause2|severity2|condition_code3|cause3|severity3|trees_measurement_comment"; if (!are_headers_valid(headers)) { violations[CSVFILENAME FS "headers" FS  "names" FS "csv headers are invalid" FS "error"]=1; exit 0; } }
action ~ /validate/ && NR > 1 { pkey=company "-" company_plot_number "-" measurement_number "-" tree_number; if(keys[pkey]) { if (dupkeys[pkey]) dupkeys[pkey]++; else dupkeys[pkey] = 1 } else { keys[pkey] = NR } }
action == "validate" && NR > 1 && NF != field_width { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "invalid-column-count" FS "error" FS  "row " NR " has an invalid column count" FS ""} 
action == "validate:summary" && NR > 1 && NF != field_width { key=CSVFILENAME FS "" FS  "invalid-column-count" FS "row " NR " has an invalid column count" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && company == "" { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "required" FS "error" FS  "company value is required but was empty" FS "company"} 
action == "validate:summary" && NR > 1 && company == "" { key=CSVFILENAME FS "company" FS  "required" FS "company value is required but was empty" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && company != "" && company !~ /^(AINS|ALPC|ANC|APLY|BLUE|CFPL|CFS|DAIS|FOFP|GOA|HPFP|HLFP|MDFP|MWWC|SFPI|SLPC|SPRA|SUND|TOLK|TOSL|UNKN|UOA|VAND|WFML|WYGP|WYPM)$/ { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "pattern" FS "error" FS  "company value should match: /^(AINS|ALPC|ANC|APLY|BLUE|CFPL|CFS|DAIS|FOFP|GOA|HPFP|HLFP|MDFP|MWWC|SFPI|SLPC|SPRA|SUND|TOLK|TOSL|UNKN|UOA|VAND|WFML|WYGP|WYPM)$/" FS "company"} 
action == "validate:summary" && NR > 1 && company != "" && company !~ /^(AINS|ALPC|ANC|APLY|BLUE|CFPL|CFS|DAIS|FOFP|GOA|HPFP|HLFP|MDFP|MWWC|SFPI|SLPC|SPRA|SUND|TOLK|TOSL|UNKN|UOA|VAND|WFML|WYGP|WYPM)$/ { key=CSVFILENAME FS "company" FS  "pattern" FS "company value should match: /^(AINS|ALPC|ANC|APLY|BLUE|CFPL|CFS|DAIS|FOFP|GOA|HPFP|HLFP|MDFP|MWWC|SFPI|SLPC|SPRA|SUND|TOLK|TOSL|UNKN|UOA|VAND|WFML|WYGP|WYPM)$/" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && company_plot_number == "" { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "required" FS "error" FS  "company_plot_number value is required but was empty" FS "company_plot_number"} 
action == "validate:summary" && NR > 1 && company_plot_number == "" { key=CSVFILENAME FS "company_plot_number" FS  "required" FS "company_plot_number value is required but was empty" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && company_plot_number != "" && length(company_plot_number) > 15 { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "maxLength" FS "error" FS  "company_plot_number max length is: 15" FS "company_plot_number"} 
action == "validate:summary" && NR > 1 && company_plot_number != "" && length(company_plot_number) > 15 { key=CSVFILENAME FS "company_plot_number" FS  "maxLength" FS "company_plot_number max length is: 15" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && measurement_number && !is_integer(measurement_number) { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "type" FS "error" FS  "measurement_number should be an integer" FS "measurement_number"} 
action == "validate:summary" && NR > 1 && measurement_number && !is_integer(measurement_number) { key=CSVFILENAME FS "measurement_number" FS  "type" FS "measurement_number should be an integer" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && measurement_number == "" { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "required" FS "error" FS  "measurement_number value is required but was empty" FS "measurement_number"} 
action == "validate:summary" && NR > 1 && measurement_number == "" { key=CSVFILENAME FS "measurement_number" FS  "required" FS "measurement_number value is required but was empty" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && measurement_number != "" && length(measurement_number) > 2 { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "maxLength" FS "error" FS  "measurement_number max length is: 2" FS "measurement_number"} 
action == "validate:summary" && NR > 1 && measurement_number != "" && length(measurement_number) > 2 { key=CSVFILENAME FS "measurement_number" FS  "maxLength" FS "measurement_number max length is: 2" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && tree_number && !is_integer(tree_number) { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "type" FS "error" FS  "tree_number should be an integer" FS "tree_number"} 
action == "validate:summary" && NR > 1 && tree_number && !is_integer(tree_number) { key=CSVFILENAME FS "tree_number" FS  "type" FS "tree_number should be an integer" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && tree_number == "" { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "required" FS "error" FS  "tree_number value is required but was empty" FS "tree_number"} 
action == "validate:summary" && NR > 1 && tree_number == "" { key=CSVFILENAME FS "tree_number" FS  "required" FS "tree_number value is required but was empty" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && tree_number != "" && tree_number < 0 { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "minimum" FS "error" FS  "tree_number value should be greater or equal to: 0" FS "tree_number"} 
action == "validate:summary" && NR > 1 && tree_number != "" && tree_number < 0 { key=CSVFILENAME FS "tree_number" FS  "minimum" FS "tree_number value should be greater or equal to: 0" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && tree_number != "" && tree_number > 9999999 { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "maximum" FS "error" FS  "tree_number value should be less or equal to: 9999999" FS "tree_number"} 
action == "validate:summary" && NR > 1 && tree_number != "" && tree_number > 9999999 { key=CSVFILENAME FS "tree_number" FS  "maximum" FS "tree_number value should be less or equal to: 9999999" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && tree_type == "" { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "required" FS "error" FS  "tree_type value is required but was empty" FS "tree_type"} 
action == "validate:summary" && NR > 1 && tree_type == "" { key=CSVFILENAME FS "tree_type" FS  "required" FS "tree_type value is required but was empty" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && tree_type != "" && tree_type !~ /^(B|ES|ET|R1|R2|R3|R4|R5|R6|R7|R8|R9|R10|S|T)$/ { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "pattern" FS "error" FS  "tree_type value should match: /^(B|ES|ET|R1|R2|R3|R4|R5|R6|R7|R8|R9|R10|S|T)$/" FS "tree_type"} 
action == "validate:summary" && NR > 1 && tree_type != "" && tree_type !~ /^(B|ES|ET|R1|R2|R3|R4|R5|R6|R7|R8|R9|R10|S|T)$/ { key=CSVFILENAME FS "tree_type" FS  "pattern" FS "tree_type value should match: /^(B|ES|ET|R1|R2|R3|R4|R5|R6|R7|R8|R9|R10|S|T)$/" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && dbh && !is_number(dbh) { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "type" FS "error" FS  "dbh should be a number" FS "dbh"} 
action == "validate:summary" && NR > 1 && dbh && !is_number(dbh) { key=CSVFILENAME FS "dbh" FS  "type" FS "dbh should be a number" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && dbh != "" && dbh < 0.1 { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "minimum" FS "error" FS  "dbh value should be greater or equal to: 0.1" FS "dbh"} 
action == "validate:summary" && NR > 1 && dbh != "" && dbh < 0.1 { key=CSVFILENAME FS "dbh" FS  "minimum" FS "dbh value should be greater or equal to: 0.1" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && dbh != "" && dbh > 120 { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "maximum" FS "error" FS  "dbh value should be less or equal to: 120" FS "dbh"} 
action == "validate:summary" && NR > 1 && dbh != "" && dbh > 120 { key=CSVFILENAME FS "dbh" FS  "maximum" FS "dbh value should be less or equal to: 120" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && dbh != "" && dbh !~ /^[0-9]*.[0-9]{1}$/ { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "pattern" FS "error" FS  "dbh value should match: /^[0-9]*.[0-9]{1}$/" FS "dbh"} 
action == "validate:summary" && NR > 1 && dbh != "" && dbh !~ /^[0-9]*.[0-9]{1}$/ { key=CSVFILENAME FS "dbh" FS  "pattern" FS "dbh value should match: /^[0-9]*.[0-9]{1}$/" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && dbh_height && !is_number(dbh_height) { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "type" FS "error" FS  "dbh_height should be a number" FS "dbh_height"} 
action == "validate:summary" && NR > 1 && dbh_height && !is_number(dbh_height) { key=CSVFILENAME FS "dbh_height" FS  "type" FS "dbh_height should be a number" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && dbh_height != "" && dbh_height < 1.1 { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "minimum" FS "error" FS  "dbh_height value should be greater or equal to: 1.1" FS "dbh_height"} 
action == "validate:summary" && NR > 1 && dbh_height != "" && dbh_height < 1.1 { key=CSVFILENAME FS "dbh_height" FS  "minimum" FS "dbh_height value should be greater or equal to: 1.1" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && dbh_height != "" && dbh_height > 1.5 { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "maximum" FS "error" FS  "dbh_height value should be less or equal to: 1.5" FS "dbh_height"} 
action == "validate:summary" && NR > 1 && dbh_height != "" && dbh_height > 1.5 { key=CSVFILENAME FS "dbh_height" FS  "maximum" FS "dbh_height value should be less or equal to: 1.5" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && dbh_height != "" && dbh_height !~ /^[0-9].[0-9]{2}$/ { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "pattern" FS "error" FS  "dbh_height value should match: /^[0-9].[0-9]{2}$/" FS "dbh_height"} 
action == "validate:summary" && NR > 1 && dbh_height != "" && dbh_height !~ /^[0-9].[0-9]{2}$/ { key=CSVFILENAME FS "dbh_height" FS  "pattern" FS "dbh_height value should match: /^[0-9].[0-9]{2}$/" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && rcd && !is_number(rcd) { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "type" FS "error" FS  "rcd should be a number" FS "rcd"} 
action == "validate:summary" && NR > 1 && rcd && !is_number(rcd) { key=CSVFILENAME FS "rcd" FS  "type" FS "rcd should be a number" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && rcd != "" && rcd < 0.1 { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "minimum" FS "error" FS  "rcd value should be greater or equal to: 0.1" FS "rcd"} 
action == "validate:summary" && NR > 1 && rcd != "" && rcd < 0.1 { key=CSVFILENAME FS "rcd" FS  "minimum" FS "rcd value should be greater or equal to: 0.1" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && rcd != "" && rcd > 15 { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "maximum" FS "error" FS  "rcd value should be less or equal to: 15" FS "rcd"} 
action == "validate:summary" && NR > 1 && rcd != "" && rcd > 15 { key=CSVFILENAME FS "rcd" FS  "maximum" FS "rcd value should be less or equal to: 15" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && rcd != "" && rcd !~ /^[0-9]*.[0-9]{1}$/ { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "pattern" FS "error" FS  "rcd value should match: /^[0-9]*.[0-9]{1}$/" FS "rcd"} 
action == "validate:summary" && NR > 1 && rcd != "" && rcd !~ /^[0-9]*.[0-9]{1}$/ { key=CSVFILENAME FS "rcd" FS  "pattern" FS "rcd value should match: /^[0-9]*.[0-9]{1}$/" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && rcd_height && !is_number(rcd_height) { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "type" FS "error" FS  "rcd_height should be a number" FS "rcd_height"} 
action == "validate:summary" && NR > 1 && rcd_height && !is_number(rcd_height) { key=CSVFILENAME FS "rcd_height" FS  "type" FS "rcd_height should be a number" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && rcd_height != "" && rcd_height < 0 { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "minimum" FS "error" FS  "rcd_height value should be greater or equal to: 0" FS "rcd_height"} 
action == "validate:summary" && NR > 1 && rcd_height != "" && rcd_height < 0 { key=CSVFILENAME FS "rcd_height" FS  "minimum" FS "rcd_height value should be greater or equal to: 0" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && rcd_height != "" && rcd_height > 0.3 { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "maximum" FS "error" FS  "rcd_height value should be less or equal to: 0.3" FS "rcd_height"} 
action == "validate:summary" && NR > 1 && rcd_height != "" && rcd_height > 0.3 { key=CSVFILENAME FS "rcd_height" FS  "maximum" FS "rcd_height value should be less or equal to: 0.3" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && rcd_height != "" && rcd_height !~ /^[0-9].[0-9]{2}$/ { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "pattern" FS "error" FS  "rcd_height value should match: /^[0-9].[0-9]{2}$/" FS "rcd_height"} 
action == "validate:summary" && NR > 1 && rcd_height != "" && rcd_height !~ /^[0-9].[0-9]{2}$/ { key=CSVFILENAME FS "rcd_height" FS  "pattern" FS "rcd_height value should match: /^[0-9].[0-9]{2}$/" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && height && !is_number(height) { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "type" FS "error" FS  "height should be a number" FS "height"} 
action == "validate:summary" && NR > 1 && height && !is_number(height) { key=CSVFILENAME FS "height" FS  "type" FS "height should be a number" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && height != "" && height < 0.01 { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "minimum" FS "error" FS  "height value should be greater or equal to: 0.01" FS "height"} 
action == "validate:summary" && NR > 1 && height != "" && height < 0.01 { key=CSVFILENAME FS "height" FS  "minimum" FS "height value should be greater or equal to: 0.01" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && height != "" && height > 45 { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "maximum" FS "error" FS  "height value should be less or equal to: 45" FS "height"} 
action == "validate:summary" && NR > 1 && height != "" && height > 45 { key=CSVFILENAME FS "height" FS  "maximum" FS "height value should be less or equal to: 45" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && height != "" && height !~ /^[0-9]*.[0-9]{2}$/ { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "pattern" FS "error" FS  "height value should match: /^[0-9]*.[0-9]{2}$/" FS "height"} 
action == "validate:summary" && NR > 1 && height != "" && height !~ /^[0-9]*.[0-9]{2}$/ { key=CSVFILENAME FS "height" FS  "pattern" FS "height value should match: /^[0-9]*.[0-9]{2}$/" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && crown_class == "" { log_err("warning"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "required" FS "warning" FS  "crown_class value is required but was empty" FS "crown_class"} 
action == "validate:summary" && NR > 1 && crown_class == "" { key=CSVFILENAME FS "crown_class" FS  "required" FS "crown_class value is required but was empty" FS "warning"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && crown_class != "" && crown_class !~ /^(C|D|I|N|S)$/ { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "pattern" FS "error" FS  "crown_class value should match: /^(C|D|I|N|S)$/" FS "crown_class"} 
action == "validate:summary" && NR > 1 && crown_class != "" && crown_class !~ /^(C|D|I|N|S)$/ { key=CSVFILENAME FS "crown_class" FS  "pattern" FS "crown_class value should match: /^(C|D|I|N|S)$/" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && dbh_age && !is_integer(dbh_age) { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "type" FS "error" FS  "dbh_age should be an integer" FS "dbh_age"} 
action == "validate:summary" && NR > 1 && dbh_age && !is_integer(dbh_age) { key=CSVFILENAME FS "dbh_age" FS  "type" FS "dbh_age should be an integer" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && dbh_age != "" && dbh_age < 1 { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "minimum" FS "error" FS  "dbh_age value should be greater or equal to: 1" FS "dbh_age"} 
action == "validate:summary" && NR > 1 && dbh_age != "" && dbh_age < 1 { key=CSVFILENAME FS "dbh_age" FS  "minimum" FS "dbh_age value should be greater or equal to: 1" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && dbh_age != "" && dbh_age > 350 { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "maximum" FS "error" FS  "dbh_age value should be less or equal to: 350" FS "dbh_age"} 
action == "validate:summary" && NR > 1 && dbh_age != "" && dbh_age > 350 { key=CSVFILENAME FS "dbh_age" FS  "maximum" FS "dbh_age value should be less or equal to: 350" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && stump_age && !is_integer(stump_age) { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "type" FS "error" FS  "stump_age should be an integer" FS "stump_age"} 
action == "validate:summary" && NR > 1 && stump_age && !is_integer(stump_age) { key=CSVFILENAME FS "stump_age" FS  "type" FS "stump_age should be an integer" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && stump_age != "" && stump_age < 1 { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "minimum" FS "error" FS  "stump_age value should be greater or equal to: 1" FS "stump_age"} 
action == "validate:summary" && NR > 1 && stump_age != "" && stump_age < 1 { key=CSVFILENAME FS "stump_age" FS  "minimum" FS "stump_age value should be greater or equal to: 1" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && stump_age != "" && stump_age > 350 { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "maximum" FS "error" FS  "stump_age value should be less or equal to: 350" FS "stump_age"} 
action == "validate:summary" && NR > 1 && stump_age != "" && stump_age > 350 { key=CSVFILENAME FS "stump_age" FS  "maximum" FS "stump_age value should be less or equal to: 350" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && stump_height && !is_number(stump_height) { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "type" FS "error" FS  "stump_height should be a number" FS "stump_height"} 
action == "validate:summary" && NR > 1 && stump_height && !is_number(stump_height) { key=CSVFILENAME FS "stump_height" FS  "type" FS "stump_height should be a number" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && stump_height != "" && stump_height < 0 { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "minimum" FS "error" FS  "stump_height value should be greater or equal to: 0" FS "stump_height"} 
action == "validate:summary" && NR > 1 && stump_height != "" && stump_height < 0 { key=CSVFILENAME FS "stump_height" FS  "minimum" FS "stump_height value should be greater or equal to: 0" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && stump_height != "" && stump_height > 0.3 { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "maximum" FS "error" FS  "stump_height value should be less or equal to: 0.3" FS "stump_height"} 
action == "validate:summary" && NR > 1 && stump_height != "" && stump_height > 0.3 { key=CSVFILENAME FS "stump_height" FS  "maximum" FS "stump_height value should be less or equal to: 0.3" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && stump_height != "" && stump_height !~ /^[0-9].[0-9]{2}$/ { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "pattern" FS "error" FS  "stump_height value should match: /^[0-9].[0-9]{2}$/" FS "stump_height"} 
action == "validate:summary" && NR > 1 && stump_height != "" && stump_height !~ /^[0-9].[0-9]{2}$/ { key=CSVFILENAME FS "stump_height" FS  "pattern" FS "stump_height value should match: /^[0-9].[0-9]{2}$/" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && total_age && !is_integer(total_age) { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "type" FS "error" FS  "total_age should be an integer" FS "total_age"} 
action == "validate:summary" && NR > 1 && total_age && !is_integer(total_age) { key=CSVFILENAME FS "total_age" FS  "type" FS "total_age should be an integer" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && total_age != "" && total_age < 1 { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "minimum" FS "error" FS  "total_age value should be greater or equal to: 1" FS "total_age"} 
action == "validate:summary" && NR > 1 && total_age != "" && total_age < 1 { key=CSVFILENAME FS "total_age" FS  "minimum" FS "total_age value should be greater or equal to: 1" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && total_age != "" && total_age > 350 { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "maximum" FS "error" FS  "total_age value should be less or equal to: 350" FS "total_age"} 
action == "validate:summary" && NR > 1 && total_age != "" && total_age > 350 { key=CSVFILENAME FS "total_age" FS  "maximum" FS "total_age value should be less or equal to: 350" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && htlc && !is_number(htlc) { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "type" FS "error" FS  "htlc should be a number" FS "htlc"} 
action == "validate:summary" && NR > 1 && htlc && !is_number(htlc) { key=CSVFILENAME FS "htlc" FS  "type" FS "htlc should be a number" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && htlc != "" && htlc < 0 { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "minimum" FS "error" FS  "htlc value should be greater or equal to: 0" FS "htlc"} 
action == "validate:summary" && NR > 1 && htlc != "" && htlc < 0 { key=CSVFILENAME FS "htlc" FS  "minimum" FS "htlc value should be greater or equal to: 0" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && htlc != "" && htlc > 45 { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "maximum" FS "error" FS  "htlc value should be less or equal to: 45" FS "htlc"} 
action == "validate:summary" && NR > 1 && htlc != "" && htlc > 45 { key=CSVFILENAME FS "htlc" FS  "maximum" FS "htlc value should be less or equal to: 45" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && htlc != "" && htlc !~ /^[0-9]*.[0-9]{2}$/ { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "pattern" FS "error" FS  "htlc value should match: /^[0-9]*.[0-9]{2}$/" FS "htlc"} 
action == "validate:summary" && NR > 1 && htlc != "" && htlc !~ /^[0-9]*.[0-9]{2}$/ { key=CSVFILENAME FS "htlc" FS  "pattern" FS "htlc value should match: /^[0-9]*.[0-9]{2}$/" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && crown_diameter_ns && !is_number(crown_diameter_ns) { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "type" FS "error" FS  "crown_diameter_ns should be a number" FS "crown_diameter_ns"} 
action == "validate:summary" && NR > 1 && crown_diameter_ns && !is_number(crown_diameter_ns) { key=CSVFILENAME FS "crown_diameter_ns" FS  "type" FS "crown_diameter_ns should be a number" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && crown_diameter_ns != "" && crown_diameter_ns < 0.01 { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "minimum" FS "error" FS  "crown_diameter_ns value should be greater or equal to: 0.01" FS "crown_diameter_ns"} 
action == "validate:summary" && NR > 1 && crown_diameter_ns != "" && crown_diameter_ns < 0.01 { key=CSVFILENAME FS "crown_diameter_ns" FS  "minimum" FS "crown_diameter_ns value should be greater or equal to: 0.01" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && crown_diameter_ns != "" && crown_diameter_ns > 20 { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "maximum" FS "error" FS  "crown_diameter_ns value should be less or equal to: 20" FS "crown_diameter_ns"} 
action == "validate:summary" && NR > 1 && crown_diameter_ns != "" && crown_diameter_ns > 20 { key=CSVFILENAME FS "crown_diameter_ns" FS  "maximum" FS "crown_diameter_ns value should be less or equal to: 20" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && crown_diameter_ns != "" && crown_diameter_ns !~ /^[0-9]*.[0-9]{2}$/ { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "pattern" FS "error" FS  "crown_diameter_ns value should match: /^[0-9]*.[0-9]{2}$/" FS "crown_diameter_ns"} 
action == "validate:summary" && NR > 1 && crown_diameter_ns != "" && crown_diameter_ns !~ /^[0-9]*.[0-9]{2}$/ { key=CSVFILENAME FS "crown_diameter_ns" FS  "pattern" FS "crown_diameter_ns value should match: /^[0-9]*.[0-9]{2}$/" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && crown_diameter_ew && !is_number(crown_diameter_ew) { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "type" FS "error" FS  "crown_diameter_ew should be a number" FS "crown_diameter_ew"} 
action == "validate:summary" && NR > 1 && crown_diameter_ew && !is_number(crown_diameter_ew) { key=CSVFILENAME FS "crown_diameter_ew" FS  "type" FS "crown_diameter_ew should be a number" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && crown_diameter_ew != "" && crown_diameter_ew < 0.01 { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "minimum" FS "error" FS  "crown_diameter_ew value should be greater or equal to: 0.01" FS "crown_diameter_ew"} 
action == "validate:summary" && NR > 1 && crown_diameter_ew != "" && crown_diameter_ew < 0.01 { key=CSVFILENAME FS "crown_diameter_ew" FS  "minimum" FS "crown_diameter_ew value should be greater or equal to: 0.01" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && crown_diameter_ew != "" && crown_diameter_ew > 20 { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "maximum" FS "error" FS  "crown_diameter_ew value should be less or equal to: 20" FS "crown_diameter_ew"} 
action == "validate:summary" && NR > 1 && crown_diameter_ew != "" && crown_diameter_ew > 20 { key=CSVFILENAME FS "crown_diameter_ew" FS  "maximum" FS "crown_diameter_ew value should be less or equal to: 20" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && crown_diameter_ew != "" && crown_diameter_ew !~ /^[0-9]*.[0-9]{2}$/ { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "pattern" FS "error" FS  "crown_diameter_ew value should match: /^[0-9]*.[0-9]{2}$/" FS "crown_diameter_ew"} 
action == "validate:summary" && NR > 1 && crown_diameter_ew != "" && crown_diameter_ew !~ /^[0-9]*.[0-9]{2}$/ { key=CSVFILENAME FS "crown_diameter_ew" FS  "pattern" FS "crown_diameter_ew value should match: /^[0-9]*.[0-9]{2}$/" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && condition_code1 && !is_integer(condition_code1) { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "type" FS "error" FS  "condition_code1 should be an integer" FS "condition_code1"} 
action == "validate:summary" && NR > 1 && condition_code1 && !is_integer(condition_code1) { key=CSVFILENAME FS "condition_code1" FS  "type" FS "condition_code1 should be an integer" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && condition_code1 == "" { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "required" FS "error" FS  "condition_code1 value is required but was empty" FS "condition_code1"} 
action == "validate:summary" && NR > 1 && condition_code1 == "" { key=CSVFILENAME FS "condition_code1" FS  "required" FS "condition_code1 value is required but was empty" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && condition_code1 != "" && condition_code1 !~ /^(0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16)$/ { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "pattern" FS "error" FS  "condition_code1 value should match: /^(0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16)$/" FS "condition_code1"} 
action == "validate:summary" && NR > 1 && condition_code1 != "" && condition_code1 !~ /^(0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16)$/ { key=CSVFILENAME FS "condition_code1" FS  "pattern" FS "condition_code1 value should match: /^(0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16)$/" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && cause1 && !is_integer(cause1) { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "type" FS "error" FS  "cause1 should be an integer" FS "cause1"} 
action == "validate:summary" && NR > 1 && cause1 && !is_integer(cause1) { key=CSVFILENAME FS "cause1" FS  "type" FS "cause1 should be an integer" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && cause1 != "" && cause1 !~ /^(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|99)$/ { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "pattern" FS "error" FS  "cause1 value should match: /^(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|99)$/" FS "cause1"} 
action == "validate:summary" && NR > 1 && cause1 != "" && cause1 !~ /^(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|99)$/ { key=CSVFILENAME FS "cause1" FS  "pattern" FS "cause1 value should match: /^(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|99)$/" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && severity1 && !is_integer(severity1) { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "type" FS "error" FS  "severity1 should be an integer" FS "severity1"} 
action == "validate:summary" && NR > 1 && severity1 && !is_integer(severity1) { key=CSVFILENAME FS "severity1" FS  "type" FS "severity1 should be an integer" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && severity1 != "" && severity1 !~ /^(1|2|3|9)$/ { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "pattern" FS "error" FS  "severity1 value should match: /^(1|2|3|9)$/" FS "severity1"} 
action == "validate:summary" && NR > 1 && severity1 != "" && severity1 !~ /^(1|2|3|9)$/ { key=CSVFILENAME FS "severity1" FS  "pattern" FS "severity1 value should match: /^(1|2|3|9)$/" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && condition_code2 && !is_integer(condition_code2) { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "type" FS "error" FS  "condition_code2 should be an integer" FS "condition_code2"} 
action == "validate:summary" && NR > 1 && condition_code2 && !is_integer(condition_code2) { key=CSVFILENAME FS "condition_code2" FS  "type" FS "condition_code2 should be an integer" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && condition_code2 != "" && condition_code2 !~ /^(3|4|5|6|7|8|9|10|11|12|16)$/ { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "pattern" FS "error" FS  "condition_code2 value should match: /^(3|4|5|6|7|8|9|10|11|12|16)$/" FS "condition_code2"} 
action == "validate:summary" && NR > 1 && condition_code2 != "" && condition_code2 !~ /^(3|4|5|6|7|8|9|10|11|12|16)$/ { key=CSVFILENAME FS "condition_code2" FS  "pattern" FS "condition_code2 value should match: /^(3|4|5|6|7|8|9|10|11|12|16)$/" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && cause2 && !is_integer(cause2) { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "type" FS "error" FS  "cause2 should be an integer" FS "cause2"} 
action == "validate:summary" && NR > 1 && cause2 && !is_integer(cause2) { key=CSVFILENAME FS "cause2" FS  "type" FS "cause2 should be an integer" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && cause2 != "" && cause2 !~ /^(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|99)$/ { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "pattern" FS "error" FS  "cause2 value should match: /^(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|99)$/" FS "cause2"} 
action == "validate:summary" && NR > 1 && cause2 != "" && cause2 !~ /^(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|99)$/ { key=CSVFILENAME FS "cause2" FS  "pattern" FS "cause2 value should match: /^(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|99)$/" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && severity2 && !is_integer(severity2) { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "type" FS "error" FS  "severity2 should be an integer" FS "severity2"} 
action == "validate:summary" && NR > 1 && severity2 && !is_integer(severity2) { key=CSVFILENAME FS "severity2" FS  "type" FS "severity2 should be an integer" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && severity2 != "" && severity2 !~ /^(1|2|3|9)$/ { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "pattern" FS "error" FS  "severity2 value should match: /^(1|2|3|9)$/" FS "severity2"} 
action == "validate:summary" && NR > 1 && severity2 != "" && severity2 !~ /^(1|2|3|9)$/ { key=CSVFILENAME FS "severity2" FS  "pattern" FS "severity2 value should match: /^(1|2|3|9)$/" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && condition_code3 && !is_integer(condition_code3) { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "type" FS "error" FS  "condition_code3 should be an integer" FS "condition_code3"} 
action == "validate:summary" && NR > 1 && condition_code3 && !is_integer(condition_code3) { key=CSVFILENAME FS "condition_code3" FS  "type" FS "condition_code3 should be an integer" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && condition_code3 != "" && condition_code3 !~ /^(3|4|5|6|7|8|9|10|11|12|16)$/ { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "pattern" FS "error" FS  "condition_code3 value should match: /^(3|4|5|6|7|8|9|10|11|12|16)$/" FS "condition_code3"} 
action == "validate:summary" && NR > 1 && condition_code3 != "" && condition_code3 !~ /^(3|4|5|6|7|8|9|10|11|12|16)$/ { key=CSVFILENAME FS "condition_code3" FS  "pattern" FS "condition_code3 value should match: /^(3|4|5|6|7|8|9|10|11|12|16)$/" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && cause3 && !is_integer(cause3) { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "type" FS "error" FS  "cause3 should be an integer" FS "cause3"} 
action == "validate:summary" && NR > 1 && cause3 && !is_integer(cause3) { key=CSVFILENAME FS "cause3" FS  "type" FS "cause3 should be an integer" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && cause3 != "" && cause3 !~ /^(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|99)$/ { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "pattern" FS "error" FS  "cause3 value should match: /^(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|99)$/" FS "cause3"} 
action == "validate:summary" && NR > 1 && cause3 != "" && cause3 !~ /^(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|99)$/ { key=CSVFILENAME FS "cause3" FS  "pattern" FS "cause3 value should match: /^(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|99)$/" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && severity3 && !is_integer(severity3) { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "type" FS "error" FS  "severity3 should be an integer" FS "severity3"} 
action == "validate:summary" && NR > 1 && severity3 && !is_integer(severity3) { key=CSVFILENAME FS "severity3" FS  "type" FS "severity3 should be an integer" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && severity3 != "" && severity3 !~ /^(1|2|3|9)$/ { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "pattern" FS "error" FS  "severity3 value should match: /^(1|2|3|9)$/" FS "severity3"} 
action == "validate:summary" && NR > 1 && severity3 != "" && severity3 !~ /^(1|2|3|9)$/ { key=CSVFILENAME FS "severity3" FS  "pattern" FS "severity3 value should match: /^(1|2|3|9)$/" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && trees_measurement_comment != "" && length(trees_measurement_comment) > 250 { log_err("error"); print  NR FS CSVFILENAME FS company "-" company_plot_number "-" measurement_number "-" tree_number FS "maxLength" FS "error" FS  "trees_measurement_comment max length is: 250" FS "trees_measurement_comment"} 
action == "validate:summary" && NR > 1 && trees_measurement_comment != "" && length(trees_measurement_comment) > 250 { key=CSVFILENAME FS "trees_measurement_comment" FS  "maxLength" FS "trees_measurement_comment max length is: 250" FS "error"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 

# sanitize rules
action ~ /^(sanitize|insert)$/ && NR > 1 {
    if (stump_age == "") $13 = "\\N"
    if (dbh == "") $6 = "\\N"
    if (tree_number == "") $4 = "\\N"
    if (measurement_number == "") $3 = "\\N"
    if (crown_diameter_ew == "") $18 = "\\N"
    if (condition_code1 == "") $19 = "\\N"
    if (rcd_height == "") $9 = "\\N"
    if (rcd == "") $8 = "\\N"
    if (condition_code2 == "") $22 = "\\N"
    if (cause1 == "") $20 = "\\N"
    if (height == "") $10 = "\\N"
    if (dbh_height == "") $7 = "\\N"
    if (trees_measurement_comment == "") $28 = "\\N"
    if (condition_code3 == "") $25 = "\\N"
    if (cause2 == "") $23 = "\\N"
    if (dbh_age == "") $12 = "\\N"
    if (company_plot_number == "") $2 = "\\N"
    if (cause3 == "") $26 = "\\N"
    if (htlc == "") $16 = "\\N"
    if (crown_diameter_ns == "") $17 = "\\N"
    if (total_age == "") $15 = "\\N"
    if (stump_height == "") $14 = "\\N"
    if (tree_type == "") $5 = "\\N"
    if (severity1 == "") $21 = "\\N"
    if (crown_class == "") $11 = "\\N"
    if (company == "") $1 = "\\N"
    if (severity2 == "") $24 = "\\N"
    if (severity3 == "") $27 = "\\N"
}

# action handlers
action == "insert" && NR == 1 {
    print "SET client_encoding = 'UTF8';"
    print "COPY " schema "trees_measurement (" addfields FS "source_row_index" FS $0 ") FROM stdin;"
}
action == "insert" && NR > 1 {
   record = addvals "\t" NR
   for (i = 1; i <= NF; i++) {
       record = record "\t" $i
   }
   print record
}
action == "table" && NR == 1 {
     print "CREATE TABLE IF NOT EXISTS trees_measurement (company ,company_plot_number ,measurement_number ,tree_number ,tree_type ,dbh ,dbh_height ,rcd ,rcd_height ,height ,crown_class ,dbh_age ,stump_age ,stump_height ,total_age ,htlc ,crown_diameter_ns ,crown_diameter_ew ,condition_code1 ,cause1 ,severity1 ,condition_code2 ,cause2 ,severity2 ,condition_code3 ,cause3 ,severity3 ,trees_measurement_comment , CONSTRAINT trees_measurement_pkey PRIMARY KEY (company,company_plot_number,measurement_number,tree_number) , CONSTRAINT trees_measurement_trees_fkey FOREIGN KEY (company,company_plot_number,tree_number) REFERENCES trees (company,company_plot_number,tree_number) MATCH FULL ON UPDATE CASCADE ON DELETE NO ACTION);"
}
action == "sanitize" { print }
# la fin
END {
    if (action == "validate:summary" && length(dupkeys) > 0) for (dup in dupkeys) { violation=CSVFILENAME FS "company|company_plot_number|measurement_number|tree_number" FS  "duplicate" FS dup " violates pkey" FS "error"; violations[violation] = dupkeys[dup]}
    if (action == "validate:summary") { if (length(violations) > 0) for (violation in violations) { print violation FS violations[violation]; } }
    if (action == "insert") print "\\." RS
    if (action == "validate" && options["summary"] == "true") { print RS "violation summary: " RS "   counts:   " RS "      total: " err_count; print_cats(cats); }
}
