#!/usr/bin/awk -F, -f

# generated by: awk-csvalid https://github.com/tesera/awk-csvalid

# awk-csvalid csv toolset generator: https://github.com/tesera/awk-csvalid
# usage:
#    validate:     awk -f action=validate validator.awk > violations.txt
#    create table: awk -v action=table -f validator.awk | psql afgo_dev
#    sanitize csv: awk -v action=sanitize -f validator.awk > sanitized.csv
#    insert sql:   awk -v action=insert -f validator.awk | psql afgo_dev

# awk is a simple unix text file parser: http://www.gnu.org/software/gawk/manual/gawk.html
# awk primer:
#    NR = number/index current record
#    RS = record seperator new line i.e. \n
#    FS = field seperator i.e. ,
#    /pattern/ { expression } = if pattern is truthy run expression

BEGIN {
    FS=","; OFS=","; err_count=0; cats["na"]=0;
    if(!action) action = "validate"
    summary_header="file_name,field_name,rule,message,violation_count"
}

# builtin helper functions
function eql(x,y) {v=1; for (i in x) v=(v&&x[i]==y[i]); return v;}
function are_headers_valid(valid_headers) { v=0; split($0, h, ","); split(valid_headers, vh, "|"); return eql(h, vh); }
function is_unique(i, val) { if (vals[i,val]) { return 0; } else { vals[i,val] = 1; return 1; } }
function is_numeric(x){ return(x==x+0) }
function print_cats(categories) { for (category in categories) { if (categories[category]) print "      " category ": " categories[category]; } }
function log_err(cat) { cats[cat]++; err_count++; }


#get rid of the evil windows cr
{ sub("\r$", "") }


# make header index/map
NR > 1 {
    condition_code2=$22
    company_plot_number=$2
    cause2=$23
    measurement_number=$3
    severity2=$24
    tree_number=$4
    condition_code3=$25
    tree_type=$5
    cause3=$26
    dbh=$6
    severity3=$27
    dbh_height=$7
    trees_measurement_comment=$28
    rcd=$8
    rcd_height=$9
    height=$10
    crown_class=$11
    dbh_age=$12
    stump_age=$13
    stump_height=$14
    total_age=$15
    htlc=$16
    crown_diameter_ns=$17
    crown_diameter_ew=$18
    condition_code1=$19
    cause1=$20
    severity1=$21
    company=$1
}

# awk rules based on user csv ruleset
NR == 1 && action == "validate" { headers="company|company_plot_number|measurement_number|tree_number|tree_type|dbh|dbh_height|rcd|rcd_height|height|crown_class|dbh_age|stump_age|stump_height|total_age|htlc|crown_diameter_ns|crown_diameter_ew|condition_code1|cause1|severity1|condition_code2|cause2|severity2|condition_code3|cause3|severity3|trees_measurement_comment"; if (!are_headers_valid(headers)) { gsub(/\|/, FS, headers); print RS "INVALID HEADERS IN " CSVFILENAME RS "WAS: " RS $0 RS "EXPECTED:" RS headers RS; exit 0; } }
NR == 1 && action == "validate:summary" { headers="company|company_plot_number|measurement_number|tree_number|tree_type|dbh|dbh_height|rcd|rcd_height|height|crown_class|dbh_age|stump_age|stump_height|total_age|htlc|crown_diameter_ns|crown_diameter_ew|condition_code1|cause1|severity1|condition_code2|cause2|severity2|condition_code3|cause3|severity3|trees_measurement_comment"; if (!are_headers_valid(headers)) { violations[CSVFILENAME FS "headers" FS  "names" FS "csv headers are invalid"]=1; exit 0; } }
action ~ /validate/ && NR > 1 { pkey=company "-" company_plot_number "-" measurement_number "-" tree_number; if(keys[pkey]) { if (dupkeys[pkey]) dupkeys[pkey]++; else dupkeys[pkey] = 1 } else { keys[pkey] = NR } }
action == "validate" && NR > 1 && company == "" { log_err("error"); print "Field company in " CSVFILENAME " line " NR " is required" RS $0 RS; } 
action == "validate:summary" && NR > 1 && company == "" { key=CSVFILENAME FS "company" FS  "required" FS "value is required but was empty"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && company != "" && company !~ /^(AINS|GOA|APLY|ALPC|ANC|BLUE|CFPL|CFS|DAIS|FOFP|BUCH|MDFP|MWWC|SLPC|SPRA|SUND|SFPI|HLFP|TOLK|TOSL|UOA|VAND|WFML|WYGP|WYPM|UNKN|HPFP)$/ { log_err("error"); print "company in " CSVFILENAME " line " NR " should match the following pattern /^(AINS|GOA|APLY|ALPC|ANC|BLUE|CFPL|CFS|DAIS|FOFP|BUCH|MDFP|MWWC|SLPC|SPRA|SUND|SFPI|HLFP|TOLK|TOSL|UOA|VAND|WFML|WYGP|WYPM|UNKN|HPFP)$/ and was " company " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && company != "" && company !~ /^(AINS|GOA|APLY|ALPC|ANC|BLUE|CFPL|CFS|DAIS|FOFP|BUCH|MDFP|MWWC|SLPC|SPRA|SUND|SFPI|HLFP|TOLK|TOSL|UOA|VAND|WFML|WYGP|WYPM|UNKN|HPFP)$/ { key=CSVFILENAME FS "company" FS  "pattern" FS "value should match: /^(AINS|GOA|APLY|ALPC|ANC|BLUE|CFPL|CFS|DAIS|FOFP|BUCH|MDFP|MWWC|SLPC|SPRA|SUND|SFPI|HLFP|TOLK|TOSL|UOA|VAND|WFML|WYGP|WYPM|UNKN|HPFP)$/"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && company_plot_number == "" { log_err("error"); print "Field company_plot_number in " CSVFILENAME " line " NR " is required" RS $0 RS; } 
action == "validate:summary" && NR > 1 && company_plot_number == "" { key=CSVFILENAME FS "company_plot_number" FS  "required" FS "value is required but was empty"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && company_plot_number != "" && length(company_plot_number) > 15 { log_err("error"); print "company_plot_number length in " CSVFILENAME " line " NR " should be less than 15 and was " length(company_plot_number) " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && company_plot_number != "" && length(company_plot_number) > 15 { key=CSVFILENAME FS "company_plot_number" FS  "maxLength" FS "max length is: 15"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && measurement_number && !is_numeric(measurement_number) { log_err("error"); print "Field measurement_number in " CSVFILENAME " line " NR " should be a numeric but was " measurement_number " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && measurement_number && !is_numeric(measurement_number) { key=CSVFILENAME FS "measurement_number" FS  "type" FS "max length is: 15"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && measurement_number == "" { log_err("error"); print "Field measurement_number in " CSVFILENAME " line " NR " is required" RS $0 RS; } 
action == "validate:summary" && NR > 1 && measurement_number == "" { key=CSVFILENAME FS "measurement_number" FS  "required" FS "value is required but was empty"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && measurement_number != "" && length(measurement_number) > 2 { log_err("error"); print "measurement_number length in " CSVFILENAME " line " NR " should be less than 2 and was " length(measurement_number) " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && measurement_number != "" && length(measurement_number) > 2 { key=CSVFILENAME FS "measurement_number" FS  "maxLength" FS "max length is: 2"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && tree_number && !is_numeric(tree_number) { log_err("error"); print "Field tree_number in " CSVFILENAME " line " NR " should be a numeric but was " tree_number " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && tree_number && !is_numeric(tree_number) { key=CSVFILENAME FS "tree_number" FS  "type" FS "max length is: 2"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && tree_number != "" && tree_number < 1 { log_err("error"); print "tree_number in " CSVFILENAME " line " NR " should be greater than 1 and was " tree_number " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && tree_number != "" && tree_number < 1 { key=CSVFILENAME FS "tree_number" FS  "minimum" FS "value should be greater than: 1"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && tree_number != "" && tree_number > 999999 { log_err("error"); print "tree_number in " CSVFILENAME " line " NR " should be less than 999999 and was " tree_number " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && tree_number != "" && tree_number > 999999 { key=CSVFILENAME FS "tree_number" FS  "maximum" FS "value should be less than: 999999"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && tree_type == "" { log_err("error"); print "Field tree_type in " CSVFILENAME " line " NR " is required" RS $0 RS; } 
action == "validate:summary" && NR > 1 && tree_type == "" { key=CSVFILENAME FS "tree_type" FS  "required" FS "value is required but was empty"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && tree_type != "" && tree_type !~ /^(T|S|PS|PO|B|R1|R2|R3|R4|R5|R6|R7|R8|R9|R10)$/ { log_err("error"); print "tree_type in " CSVFILENAME " line " NR " should match the following pattern /^(T|S|PS|PO|B|R1|R2|R3|R4|R5|R6|R7|R8|R9|R10)$/ and was " tree_type " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && tree_type != "" && tree_type !~ /^(T|S|PS|PO|B|R1|R2|R3|R4|R5|R6|R7|R8|R9|R10)$/ { key=CSVFILENAME FS "tree_type" FS  "pattern" FS "value should match: /^(T|S|PS|PO|B|R1|R2|R3|R4|R5|R6|R7|R8|R9|R10)$/"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && dbh && !is_numeric(dbh) { log_err("warning"); print "Field dbh in " CSVFILENAME " line " NR " should be a numeric but was " dbh " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && dbh && !is_numeric(dbh) { key=CSVFILENAME FS "dbh" FS  "type" FS "value should match: /^(T|S|PS|PO|B|R1|R2|R3|R4|R5|R6|R7|R8|R9|R10)$/"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && rcd=="" && dbh == "" { log_err("warning"); print "Field dbh in " CSVFILENAME " line " NR " is required if rcd==""" RS $0 RS; } 
action == "validate:summary" && NR > 1 && rcd=="" && dbh == "" { key=CSVFILENAME FS "dbh" FS  "required" FS "value is required if rcd=="""; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && dbh != "" && dbh < 0.1 { log_err("warning"); print "dbh in " CSVFILENAME " line " NR " should be greater than 0.1 and was " dbh " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && dbh != "" && dbh < 0.1 { key=CSVFILENAME FS "dbh" FS  "minimum" FS "value should be greater than: 0.1"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && dbh != "" && dbh > 120 { log_err("warning"); print "dbh in " CSVFILENAME " line " NR " should be less than 120 and was " dbh " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && dbh != "" && dbh > 120 { key=CSVFILENAME FS "dbh" FS  "maximum" FS "value should be less than: 120"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && dbh_height && !is_numeric(dbh_height) { log_err("warning"); print "Field dbh_height in " CSVFILENAME " line " NR " should be a numeric but was " dbh_height " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && dbh_height && !is_numeric(dbh_height) { key=CSVFILENAME FS "dbh_height" FS  "type" FS "value should be less than: 120"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && dbh!="" && dbh_height == "" { log_err("warning"); print "Field dbh_height in " CSVFILENAME " line " NR " is required if dbh!=""" RS $0 RS; } 
action == "validate:summary" && NR > 1 && dbh!="" && dbh_height == "" { key=CSVFILENAME FS "dbh_height" FS  "required" FS "value is required if dbh!="""; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && dbh_height != "" && dbh_height < 1.1 { log_err("warning"); print "dbh_height in " CSVFILENAME " line " NR " should be greater than 1.1 and was " dbh_height " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && dbh_height != "" && dbh_height < 1.1 { key=CSVFILENAME FS "dbh_height" FS  "minimum" FS "value should be greater than: 1.1"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && dbh_height != "" && dbh_height > 1.5 { log_err("warning"); print "dbh_height in " CSVFILENAME " line " NR " should be less than 1.5 and was " dbh_height " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && dbh_height != "" && dbh_height > 1.5 { key=CSVFILENAME FS "dbh_height" FS  "maximum" FS "value should be less than: 1.5"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && rcd && !is_numeric(rcd) { log_err("warning"); print "Field rcd in " CSVFILENAME " line " NR " should be a numeric but was " rcd " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && rcd && !is_numeric(rcd) { key=CSVFILENAME FS "rcd" FS  "type" FS "value should be less than: 1.5"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && dbh=="" && rcd == "" { log_err("warning"); print "Field rcd in " CSVFILENAME " line " NR " is required if dbh==""" RS $0 RS; } 
action == "validate:summary" && NR > 1 && dbh=="" && rcd == "" { key=CSVFILENAME FS "rcd" FS  "required" FS "value is required if dbh=="""; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && rcd != "" && rcd < 0.1 { log_err("warning"); print "rcd in " CSVFILENAME " line " NR " should be greater than 0.1 and was " rcd " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && rcd != "" && rcd < 0.1 { key=CSVFILENAME FS "rcd" FS  "minimum" FS "value should be greater than: 0.1"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && rcd != "" && rcd > 15 { log_err("warning"); print "rcd in " CSVFILENAME " line " NR " should be less than 15 and was " rcd " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && rcd != "" && rcd > 15 { key=CSVFILENAME FS "rcd" FS  "maximum" FS "value should be less than: 15"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && rcd_height && !is_numeric(rcd_height) { log_err("warning"); print "Field rcd_height in " CSVFILENAME " line " NR " should be a numeric but was " rcd_height " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && rcd_height && !is_numeric(rcd_height) { key=CSVFILENAME FS "rcd_height" FS  "type" FS "value should be less than: 15"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && rcd!="" && rcd_height == "" { log_err("warning"); print "Field rcd_height in " CSVFILENAME " line " NR " is required if rcd!=""" RS $0 RS; } 
action == "validate:summary" && NR > 1 && rcd!="" && rcd_height == "" { key=CSVFILENAME FS "rcd_height" FS  "required" FS "value is required if rcd!="""; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && rcd_height != "" && rcd_height < 0 { log_err("warning"); print "rcd_height in " CSVFILENAME " line " NR " should be greater than 0 and was " rcd_height " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && rcd_height != "" && rcd_height < 0 { key=CSVFILENAME FS "rcd_height" FS  "minimum" FS "value should be greater than: 0"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && rcd_height != "" && rcd_height > 0.3 { log_err("warning"); print "rcd_height in " CSVFILENAME " line " NR " should be less than 0.3 and was " rcd_height " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && rcd_height != "" && rcd_height > 0.3 { key=CSVFILENAME FS "rcd_height" FS  "maximum" FS "value should be less than: 0.3"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && height && !is_numeric(height) { log_err("warning"); print "Field height in " CSVFILENAME " line " NR " should be a numeric but was " height " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && height && !is_numeric(height) { key=CSVFILENAME FS "height" FS  "type" FS "value should be less than: 0.3"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && height != "" && height < 0 { log_err("warning"); print "height in " CSVFILENAME " line " NR " should be greater than 0 and was " height " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && height != "" && height < 0 { key=CSVFILENAME FS "height" FS  "minimum" FS "value should be greater than: 0"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && height != "" && height > 45 { log_err("warning"); print "height in " CSVFILENAME " line " NR " should be less than 45 and was " height " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && height != "" && height > 45 { key=CSVFILENAME FS "height" FS  "maximum" FS "value should be less than: 45"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && crown_class != "" && crown_class !~ /^(D|C|I|S|N)$/ { log_err("warning"); print "crown_class in " CSVFILENAME " line " NR " should match the following pattern /^(D|C|I|S|N)$/ and was " crown_class " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && crown_class != "" && crown_class !~ /^(D|C|I|S|N)$/ { key=CSVFILENAME FS "crown_class" FS  "pattern" FS "value should match: /^(D|C|I|S|N)$/"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && dbh_age && !is_numeric(dbh_age) { log_err("warning"); print "Field dbh_age in " CSVFILENAME " line " NR " should be a numeric but was " dbh_age " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && dbh_age && !is_numeric(dbh_age) { key=CSVFILENAME FS "dbh_age" FS  "type" FS "value should match: /^(D|C|I|S|N)$/"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && dbh_age != "" && dbh_age < 1 { log_err("warning"); print "dbh_age in " CSVFILENAME " line " NR " should be greater than 1 and was " dbh_age " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && dbh_age != "" && dbh_age < 1 { key=CSVFILENAME FS "dbh_age" FS  "minimum" FS "value should be greater than: 1"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && dbh_age != "" && dbh_age > 350 { log_err("warning"); print "dbh_age in " CSVFILENAME " line " NR " should be less than 350 and was " dbh_age " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && dbh_age != "" && dbh_age > 350 { key=CSVFILENAME FS "dbh_age" FS  "maximum" FS "value should be less than: 350"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && stump_age && !is_numeric(stump_age) { log_err("warning"); print "Field stump_age in " CSVFILENAME " line " NR " should be a numeric but was " stump_age " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && stump_age && !is_numeric(stump_age) { key=CSVFILENAME FS "stump_age" FS  "type" FS "value should be less than: 350"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && stump_age != "" && stump_age < 1 { log_err("warning"); print "stump_age in " CSVFILENAME " line " NR " should be greater than 1 and was " stump_age " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && stump_age != "" && stump_age < 1 { key=CSVFILENAME FS "stump_age" FS  "minimum" FS "value should be greater than: 1"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && stump_age != "" && stump_age > 350 { log_err("warning"); print "stump_age in " CSVFILENAME " line " NR " should be less than 350 and was " stump_age " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && stump_age != "" && stump_age > 350 { key=CSVFILENAME FS "stump_age" FS  "maximum" FS "value should be less than: 350"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && stump_height && !is_numeric(stump_height) { log_err("warning"); print "Field stump_height in " CSVFILENAME " line " NR " should be a numeric but was " stump_height " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && stump_height && !is_numeric(stump_height) { key=CSVFILENAME FS "stump_height" FS  "type" FS "value should be less than: 350"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && stump_age!="" && stump_height == "" { log_err("warning"); print "Field stump_height in " CSVFILENAME " line " NR " is required if stump_age!=""" RS $0 RS; } 
action == "validate:summary" && NR > 1 && stump_age!="" && stump_height == "" { key=CSVFILENAME FS "stump_height" FS  "required" FS "value is required if stump_age!="""; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && stump_height != "" && stump_height < 0 { log_err("warning"); print "stump_height in " CSVFILENAME " line " NR " should be greater than 0 and was " stump_height " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && stump_height != "" && stump_height < 0 { key=CSVFILENAME FS "stump_height" FS  "minimum" FS "value should be greater than: 0"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && stump_height != "" && stump_height > 0.3 { log_err("warning"); print "stump_height in " CSVFILENAME " line " NR " should be less than 0.3 and was " stump_height " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && stump_height != "" && stump_height > 0.3 { key=CSVFILENAME FS "stump_height" FS  "maximum" FS "value should be less than: 0.3"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && total_age && !is_numeric(total_age) { log_err("error"); print "Field total_age in " CSVFILENAME " line " NR " should be a numeric but was " total_age " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && total_age && !is_numeric(total_age) { key=CSVFILENAME FS "total_age" FS  "type" FS "value should be less than: 0.3"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && total_age != "" && total_age < 1 { log_err("error"); print "total_age in " CSVFILENAME " line " NR " should be greater than 1 and was " total_age " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && total_age != "" && total_age < 1 { key=CSVFILENAME FS "total_age" FS  "minimum" FS "value should be greater than: 1"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && total_age != "" && total_age > 350 { log_err("error"); print "total_age in " CSVFILENAME " line " NR " should be less than 350 and was " total_age " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && total_age != "" && total_age > 350 { key=CSVFILENAME FS "total_age" FS  "maximum" FS "value should be less than: 350"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && htlc && !is_numeric(htlc) { log_err("warning"); print "Field htlc in " CSVFILENAME " line " NR " should be a numeric but was " htlc " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && htlc && !is_numeric(htlc) { key=CSVFILENAME FS "htlc" FS  "type" FS "value should be less than: 350"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && htlc != "" && htlc < 0 { log_err("warning"); print "htlc in " CSVFILENAME " line " NR " should be greater than 0 and was " htlc " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && htlc != "" && htlc < 0 { key=CSVFILENAME FS "htlc" FS  "minimum" FS "value should be greater than: 0"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && htlc != "" && htlc > 45 { log_err("warning"); print "htlc in " CSVFILENAME " line " NR " should be less than 45 and was " htlc " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && htlc != "" && htlc > 45 { key=CSVFILENAME FS "htlc" FS  "maximum" FS "value should be less than: 45"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && crown_diameter_ns && !is_numeric(crown_diameter_ns) { log_err("warning"); print "Field crown_diameter_ns in " CSVFILENAME " line " NR " should be a numeric but was " crown_diameter_ns " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && crown_diameter_ns && !is_numeric(crown_diameter_ns) { key=CSVFILENAME FS "crown_diameter_ns" FS  "type" FS "value should be less than: 45"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && crown_diameter_ns != "" && crown_diameter_ns < 1 { log_err("warning"); print "crown_diameter_ns in " CSVFILENAME " line " NR " should be greater than 1 and was " crown_diameter_ns " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && crown_diameter_ns != "" && crown_diameter_ns < 1 { key=CSVFILENAME FS "crown_diameter_ns" FS  "minimum" FS "value should be greater than: 1"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && crown_diameter_ns != "" && crown_diameter_ns > 20 { log_err("warning"); print "crown_diameter_ns in " CSVFILENAME " line " NR " should be less than 20 and was " crown_diameter_ns " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && crown_diameter_ns != "" && crown_diameter_ns > 20 { key=CSVFILENAME FS "crown_diameter_ns" FS  "maximum" FS "value should be less than: 20"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && crown_diameter_ew && !is_numeric(crown_diameter_ew) { log_err("warning"); print "Field crown_diameter_ew in " CSVFILENAME " line " NR " should be a numeric but was " crown_diameter_ew " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && crown_diameter_ew && !is_numeric(crown_diameter_ew) { key=CSVFILENAME FS "crown_diameter_ew" FS  "type" FS "value should be less than: 20"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && crown_diameter_ew != "" && crown_diameter_ew < 1 { log_err("warning"); print "crown_diameter_ew in " CSVFILENAME " line " NR " should be greater than 1 and was " crown_diameter_ew " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && crown_diameter_ew != "" && crown_diameter_ew < 1 { key=CSVFILENAME FS "crown_diameter_ew" FS  "minimum" FS "value should be greater than: 1"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && crown_diameter_ew != "" && crown_diameter_ew > 20 { log_err("warning"); print "crown_diameter_ew in " CSVFILENAME " line " NR " should be less than 20 and was " crown_diameter_ew " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && crown_diameter_ew != "" && crown_diameter_ew > 20 { key=CSVFILENAME FS "crown_diameter_ew" FS  "maximum" FS "value should be less than: 20"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && condition_code1 && !is_numeric(condition_code1) { log_err("error"); print "Field condition_code1 in " CSVFILENAME " line " NR " should be a numeric but was " condition_code1 " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && condition_code1 && !is_numeric(condition_code1) { key=CSVFILENAME FS "condition_code1" FS  "type" FS "value should be less than: 20"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && condition_code1 == "" { log_err("error"); print "Field condition_code1 in " CSVFILENAME " line " NR " is required" RS $0 RS; } 
action == "validate:summary" && NR > 1 && condition_code1 == "" { key=CSVFILENAME FS "condition_code1" FS  "required" FS "value is required but was empty"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && condition_code1 != "" && condition_code1 !~ /^(0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16)$/ { log_err("error"); print "condition_code1 in " CSVFILENAME " line " NR " should match the following pattern /^(0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16)$/ and was " condition_code1 " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && condition_code1 != "" && condition_code1 !~ /^(0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16)$/ { key=CSVFILENAME FS "condition_code1" FS  "pattern" FS "value should match: /^(0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16)$/"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && cause1 && !is_numeric(cause1) { log_err("warning"); print "Field cause1 in " CSVFILENAME " line " NR " should be a numeric but was " cause1 " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && cause1 && !is_numeric(cause1) { key=CSVFILENAME FS "cause1" FS  "type" FS "value should match: /^(0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16)$/"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && cause1 != "" && cause1 !~ /^(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|99)$/ { log_err("warning"); print "cause1 in " CSVFILENAME " line " NR " should match the following pattern /^(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|99)$/ and was " cause1 " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && cause1 != "" && cause1 !~ /^(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|99)$/ { key=CSVFILENAME FS "cause1" FS  "pattern" FS "value should match: /^(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|99)$/"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && severity1 && !is_numeric(severity1) { log_err("warning"); print "Field severity1 in " CSVFILENAME " line " NR " should be a numeric but was " severity1 " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && severity1 && !is_numeric(severity1) { key=CSVFILENAME FS "severity1" FS  "type" FS "value should match: /^(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|99)$/"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && severity1 != "" && severity1 !~ /^(1|2|3|9)$/ { log_err("warning"); print "severity1 in " CSVFILENAME " line " NR " should match the following pattern /^(1|2|3|9)$/ and was " severity1 " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && severity1 != "" && severity1 !~ /^(1|2|3|9)$/ { key=CSVFILENAME FS "severity1" FS  "pattern" FS "value should match: /^(1|2|3|9)$/"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && condition_code2 && !is_numeric(condition_code2) { log_err("warning"); print "Field condition_code2 in " CSVFILENAME " line " NR " should be a numeric but was " condition_code2 " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && condition_code2 && !is_numeric(condition_code2) { key=CSVFILENAME FS "condition_code2" FS  "type" FS "value should match: /^(1|2|3|9)$/"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && condition_code2 != "" && condition_code2 !~ /^(0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16)$/ { log_err("warning"); print "condition_code2 in " CSVFILENAME " line " NR " should match the following pattern /^(0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16)$/ and was " condition_code2 " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && condition_code2 != "" && condition_code2 !~ /^(0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16)$/ { key=CSVFILENAME FS "condition_code2" FS  "pattern" FS "value should match: /^(0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16)$/"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && cause2 && !is_numeric(cause2) { log_err("warning"); print "Field cause2 in " CSVFILENAME " line " NR " should be a numeric but was " cause2 " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && cause2 && !is_numeric(cause2) { key=CSVFILENAME FS "cause2" FS  "type" FS "value should match: /^(0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16)$/"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && cause2 != "" && cause2 !~ /^(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|99)$/ { log_err("warning"); print "cause2 in " CSVFILENAME " line " NR " should match the following pattern /^(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|99)$/ and was " cause2 " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && cause2 != "" && cause2 !~ /^(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|99)$/ { key=CSVFILENAME FS "cause2" FS  "pattern" FS "value should match: /^(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|99)$/"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && severity2 && !is_numeric(severity2) { log_err("warning"); print "Field severity2 in " CSVFILENAME " line " NR " should be a numeric but was " severity2 " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && severity2 && !is_numeric(severity2) { key=CSVFILENAME FS "severity2" FS  "type" FS "value should match: /^(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|99)$/"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && severity2 != "" && severity2 !~ /^(1|2|3|9)$/ { log_err("warning"); print "severity2 in " CSVFILENAME " line " NR " should match the following pattern /^(1|2|3|9)$/ and was " severity2 " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && severity2 != "" && severity2 !~ /^(1|2|3|9)$/ { key=CSVFILENAME FS "severity2" FS  "pattern" FS "value should match: /^(1|2|3|9)$/"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && condition_code3 && !is_numeric(condition_code3) { log_err("warning"); print "Field condition_code3 in " CSVFILENAME " line " NR " should be a numeric but was " condition_code3 " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && condition_code3 && !is_numeric(condition_code3) { key=CSVFILENAME FS "condition_code3" FS  "type" FS "value should match: /^(1|2|3|9)$/"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && condition_code3 != "" && condition_code3 !~ /^(0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16)$/ { log_err("warning"); print "condition_code3 in " CSVFILENAME " line " NR " should match the following pattern /^(0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16)$/ and was " condition_code3 " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && condition_code3 != "" && condition_code3 !~ /^(0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16)$/ { key=CSVFILENAME FS "condition_code3" FS  "pattern" FS "value should match: /^(0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16)$/"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && cause3 && !is_numeric(cause3) { log_err("warning"); print "Field cause3 in " CSVFILENAME " line " NR " should be a numeric but was " cause3 " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && cause3 && !is_numeric(cause3) { key=CSVFILENAME FS "cause3" FS  "type" FS "value should match: /^(0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16)$/"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && cause3 != "" && cause3 !~ /^(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|99)$/ { log_err("warning"); print "cause3 in " CSVFILENAME " line " NR " should match the following pattern /^(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|99)$/ and was " cause3 " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && cause3 != "" && cause3 !~ /^(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|99)$/ { key=CSVFILENAME FS "cause3" FS  "pattern" FS "value should match: /^(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|99)$/"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && severity3 && !is_numeric(severity3) { log_err("warning"); print "Field severity3 in " CSVFILENAME " line " NR " should be a numeric but was " severity3 " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && severity3 && !is_numeric(severity3) { key=CSVFILENAME FS "severity3" FS  "type" FS "value should match: /^(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|99)$/"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 
action == "validate" && NR > 1 && severity3 != "" && severity3 !~ /^(1|2|3|9)$/ { log_err("warning"); print "severity3 in " CSVFILENAME " line " NR " should match the following pattern /^(1|2|3|9)$/ and was " severity3 " " RS $0 RS; } 
action == "validate:summary" && NR > 1 && severity3 != "" && severity3 !~ /^(1|2|3|9)$/ { key=CSVFILENAME FS "severity3" FS  "pattern" FS "value should match: /^(1|2|3|9)$/"; if(!violations[key]) { violations[key]=0; } violations[key]++; } 

# sanitize rules
action ~ /^(sanitize|insert)$/ && NR > 1 {
    if (stump_age == "") $13 = "-9999"
    if (height == "") $10 = "-9999"
    if (trees_measurement_comment == "") $28 = "NA"
    if (crown_diameter_ew == "") $18 = "-9999"
    if (dbh_age == "") $12 = "-9999"
    if (tree_number == "") $4 = "-9999"
    if (rcd == "") $8 = "-9999"
    if (condition_code1 == "") $19 = "NA"
    if (total_age == "") $15 = "-9999"
    if (condition_code2 == "") $22 = "NA"
    if (condition_code3 == "") $25 = "NA"
    if (cause1 == "") $20 = "NA"
    if (dbh_height == "") $7 = "-9999"
    if (measurement_number == "") $3 = "NA"
    if (cause2 == "") $23 = "NA"
    if (cause3 == "") $26 = "NA"
    if (company_plot_number == "") $2 = "NA"
    if (crown_class == "") $11 = "NA"
    if (stump_height == "") $14 = "-9999"
    if (htlc == "") $16 = "-9999"
    if (crown_diameter_ns == "") $17 = "-9999"
    if (severity1 == "") $21 = "NA"
    if (dbh == "") $6 = "-9999"
    if (severity2 == "") $24 = "NA"
    if (company == "") $1 = "NA"
    if (severity3 == "") $27 = "NA"
    if (tree_type == "") $5 = "NA"
    if (rcd_height == "") $9 = "-9999"
}

# action handlers
action == "insert" && NR == 1 {
    print "COPY trees_measurement (" addfields FS "source_row_index" FS $0 ") FROM stdin;"
}
action == "insert" && NR > 1 {
    gsub(",", "\t");
    print addvals "\t" NR "\t" $0;
}
action == "table" && NR == 1 {
     print "CREATE TABLE IF NOT EXISTS trees_measurement (company text,company_plot_number text,measurement_number text,tree_number numeric,tree_type text,dbh numeric,dbh_height numeric,rcd numeric,rcd_height numeric,height numeric,crown_class text,dbh_age numeric,stump_age numeric,stump_height numeric,total_age numeric,htlc numeric,crown_diameter_ns numeric,crown_diameter_ew numeric,condition_code1 text,cause1 text,severity1 text,condition_code2 text,cause2 text,severity2 text,condition_code3 text,cause3 text,severity3 text,trees_measurement_comment text, CONSTRAINT trees_measurement_pkey PRIMARY KEY (company,company_plot_number,measurement_number,tree_number) , CONSTRAINT trees_measurement_trees_fkey FOREIGN KEY (company,company_plot_number,tree_number) REFERENCES trees (company,company_plot_number,tree_number) MATCH FULL ON UPDATE CASCADE ON DELETE NO ACTION);"
}
action == "sanitize" { print }

# la fin
END {
    if (action == "validate:summary" && length(dupkeys) > 0) for (dup in dupkeys) { violation=CSVFILENAME FS "company|company_plot_number|measurement_number|tree_number" FS  "duplicate" FS dup " violates pkey"; violations[violation] = dupkeys[dup]}
    if (action == "validate:summary") { if (length(violations) > 0) for (violation in violations) { print violation FS violations[violation]; } }
    if (action == "validate" && options["summary"] == "true") { print RS "violation summary: " RS "   counts:   " RS "      total: " err_count; print_cats(cats); }
}
